// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: proto/apps/v0/channel.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChannelService_HealthCheck_FullMethodName = "/apps.v0.ChannelService/HealthCheck"
	ChannelService_ID_FullMethodName          = "/apps.v0.ChannelService/ID"
	ChannelService_Connect_FullMethodName     = "/apps.v0.ChannelService/Connect"
	ChannelService_Disconnect_FullMethodName  = "/apps.v0.ChannelService/Disconnect"
	ChannelService_Send_FullMethodName        = "/apps.v0.ChannelService/Send"
	ChannelService_Receive_FullMethodName     = "/apps.v0.ChannelService/Receive"
	ChannelService_Configure_FullMethodName   = "/apps.v0.ChannelService/Configure"
)

// ChannelServiceClient is the client API for ChannelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ChannelService is the interface for messaging channel apps (Discord, Telegram, etc.).
type ChannelServiceClient interface {
	// HealthCheck verifies the channel app is running.
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// ID returns the channel's unique identifier.
	ID(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*IDResponse, error)
	// Connect establishes the channel connection.
	Connect(ctx context.Context, in *ChannelConnectRequest, opts ...grpc.CallOption) (*ChannelConnectResponse, error)
	// Disconnect closes the channel connection.
	Disconnect(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ChannelDisconnectResponse, error)
	// Send sends a message to a channel.
	Send(ctx context.Context, in *ChannelSendRequest, opts ...grpc.CallOption) (*ChannelSendResponse, error)
	// Receive streams inbound messages from the channel to Nebo.
	Receive(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InboundMessage], error)
	// Configure updates the app's settings.
	Configure(ctx context.Context, in *SettingsMap, opts ...grpc.CallOption) (*Empty, error)
}

type channelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChannelServiceClient(cc grpc.ClientConnInterface) ChannelServiceClient {
	return &channelServiceClient{cc}
}

func (c *channelServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, ChannelService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelServiceClient) ID(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*IDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IDResponse)
	err := c.cc.Invoke(ctx, ChannelService_ID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelServiceClient) Connect(ctx context.Context, in *ChannelConnectRequest, opts ...grpc.CallOption) (*ChannelConnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChannelConnectResponse)
	err := c.cc.Invoke(ctx, ChannelService_Connect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelServiceClient) Disconnect(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ChannelDisconnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChannelDisconnectResponse)
	err := c.cc.Invoke(ctx, ChannelService_Disconnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelServiceClient) Send(ctx context.Context, in *ChannelSendRequest, opts ...grpc.CallOption) (*ChannelSendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChannelSendResponse)
	err := c.cc.Invoke(ctx, ChannelService_Send_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelServiceClient) Receive(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InboundMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChannelService_ServiceDesc.Streams[0], ChannelService_Receive_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, InboundMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChannelService_ReceiveClient = grpc.ServerStreamingClient[InboundMessage]

func (c *channelServiceClient) Configure(ctx context.Context, in *SettingsMap, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ChannelService_Configure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChannelServiceServer is the server API for ChannelService service.
// All implementations must embed UnimplementedChannelServiceServer
// for forward compatibility.
//
// ChannelService is the interface for messaging channel apps (Discord, Telegram, etc.).
type ChannelServiceServer interface {
	// HealthCheck verifies the channel app is running.
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// ID returns the channel's unique identifier.
	ID(context.Context, *Empty) (*IDResponse, error)
	// Connect establishes the channel connection.
	Connect(context.Context, *ChannelConnectRequest) (*ChannelConnectResponse, error)
	// Disconnect closes the channel connection.
	Disconnect(context.Context, *Empty) (*ChannelDisconnectResponse, error)
	// Send sends a message to a channel.
	Send(context.Context, *ChannelSendRequest) (*ChannelSendResponse, error)
	// Receive streams inbound messages from the channel to Nebo.
	Receive(*Empty, grpc.ServerStreamingServer[InboundMessage]) error
	// Configure updates the app's settings.
	Configure(context.Context, *SettingsMap) (*Empty, error)
	mustEmbedUnimplementedChannelServiceServer()
}

// UnimplementedChannelServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChannelServiceServer struct{}

func (UnimplementedChannelServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedChannelServiceServer) ID(context.Context, *Empty) (*IDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ID not implemented")
}
func (UnimplementedChannelServiceServer) Connect(context.Context, *ChannelConnectRequest) (*ChannelConnectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedChannelServiceServer) Disconnect(context.Context, *Empty) (*ChannelDisconnectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Disconnect not implemented")
}
func (UnimplementedChannelServiceServer) Send(context.Context, *ChannelSendRequest) (*ChannelSendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedChannelServiceServer) Receive(*Empty, grpc.ServerStreamingServer[InboundMessage]) error {
	return status.Error(codes.Unimplemented, "method Receive not implemented")
}
func (UnimplementedChannelServiceServer) Configure(context.Context, *SettingsMap) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Configure not implemented")
}
func (UnimplementedChannelServiceServer) mustEmbedUnimplementedChannelServiceServer() {}
func (UnimplementedChannelServiceServer) testEmbeddedByValue()                        {}

// UnsafeChannelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChannelServiceServer will
// result in compilation errors.
type UnsafeChannelServiceServer interface {
	mustEmbedUnimplementedChannelServiceServer()
}

func RegisterChannelServiceServer(s grpc.ServiceRegistrar, srv ChannelServiceServer) {
	// If the following call panics, it indicates UnimplementedChannelServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChannelService_ServiceDesc, srv)
}

func _ChannelService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelService_ID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServiceServer).ID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelService_ID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServiceServer).ID(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelService_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChannelConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServiceServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelService_Connect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServiceServer).Connect(ctx, req.(*ChannelConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelService_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServiceServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelService_Disconnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServiceServer).Disconnect(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelService_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChannelSendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServiceServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelService_Send_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServiceServer).Send(ctx, req.(*ChannelSendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelService_Receive_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChannelServiceServer).Receive(m, &grpc.GenericServerStream[Empty, InboundMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChannelService_ReceiveServer = grpc.ServerStreamingServer[InboundMessage]

func _ChannelService_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettingsMap)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServiceServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelService_Configure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServiceServer).Configure(ctx, req.(*SettingsMap))
	}
	return interceptor(ctx, in, info, handler)
}

// ChannelService_ServiceDesc is the grpc.ServiceDesc for ChannelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChannelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "apps.v0.ChannelService",
	HandlerType: (*ChannelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _ChannelService_HealthCheck_Handler,
		},
		{
			MethodName: "ID",
			Handler:    _ChannelService_ID_Handler,
		},
		{
			MethodName: "Connect",
			Handler:    _ChannelService_Connect_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _ChannelService_Disconnect_Handler,
		},
		{
			MethodName: "Send",
			Handler:    _ChannelService_Send_Handler,
		},
		{
			MethodName: "Configure",
			Handler:    _ChannelService_Configure_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Receive",
			Handler:       _ChannelService_Receive_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/apps/v0/channel.proto",
}
