// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.4
// source: proto/apps/v0/comm.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommNameResponse) Reset() {
	*x = CommNameResponse{}
	mi := &file_proto_apps_v0_comm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommNameResponse) ProtoMessage() {}

func (x *CommNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_comm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommNameResponse.ProtoReflect.Descriptor instead.
func (*CommNameResponse) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_comm_proto_rawDescGZIP(), []int{0}
}

func (x *CommNameResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CommVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommVersionResponse) Reset() {
	*x = CommVersionResponse{}
	mi := &file_proto_apps_v0_comm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommVersionResponse) ProtoMessage() {}

func (x *CommVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_comm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommVersionResponse.ProtoReflect.Descriptor instead.
func (*CommVersionResponse) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_comm_proto_rawDescGZIP(), []int{1}
}

func (x *CommVersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type CommConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        map[string]string      `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommConnectRequest) Reset() {
	*x = CommConnectRequest{}
	mi := &file_proto_apps_v0_comm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommConnectRequest) ProtoMessage() {}

func (x *CommConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_comm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommConnectRequest.ProtoReflect.Descriptor instead.
func (*CommConnectRequest) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_comm_proto_rawDescGZIP(), []int{2}
}

func (x *CommConnectRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type CommConnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommConnectResponse) Reset() {
	*x = CommConnectResponse{}
	mi := &file_proto_apps_v0_comm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommConnectResponse) ProtoMessage() {}

func (x *CommConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_comm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommConnectResponse.ProtoReflect.Descriptor instead.
func (*CommConnectResponse) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_comm_proto_rawDescGZIP(), []int{3}
}

func (x *CommConnectResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CommDisconnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommDisconnectResponse) Reset() {
	*x = CommDisconnectResponse{}
	mi := &file_proto_apps_v0_comm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommDisconnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommDisconnectResponse) ProtoMessage() {}

func (x *CommDisconnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_comm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommDisconnectResponse.ProtoReflect.Descriptor instead.
func (*CommDisconnectResponse) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_comm_proto_rawDescGZIP(), []int{4}
}

func (x *CommDisconnectResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CommIsConnectedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connected     bool                   `protobuf:"varint,1,opt,name=connected,proto3" json:"connected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommIsConnectedResponse) Reset() {
	*x = CommIsConnectedResponse{}
	mi := &file_proto_apps_v0_comm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommIsConnectedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommIsConnectedResponse) ProtoMessage() {}

func (x *CommIsConnectedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_comm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommIsConnectedResponse.ProtoReflect.Descriptor instead.
func (*CommIsConnectedResponse) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_comm_proto_rawDescGZIP(), []int{5}
}

func (x *CommIsConnectedResponse) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

type CommSendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *CommMessage           `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommSendRequest) Reset() {
	*x = CommSendRequest{}
	mi := &file_proto_apps_v0_comm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommSendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommSendRequest) ProtoMessage() {}

func (x *CommSendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_comm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommSendRequest.ProtoReflect.Descriptor instead.
func (*CommSendRequest) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_comm_proto_rawDescGZIP(), []int{6}
}

func (x *CommSendRequest) GetMessage() *CommMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

type CommSendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommSendResponse) Reset() {
	*x = CommSendResponse{}
	mi := &file_proto_apps_v0_comm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommSendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommSendResponse) ProtoMessage() {}

func (x *CommSendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_comm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommSendResponse.ProtoReflect.Descriptor instead.
func (*CommSendResponse) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_comm_proto_rawDescGZIP(), []int{7}
}

func (x *CommSendResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CommSubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommSubscribeRequest) Reset() {
	*x = CommSubscribeRequest{}
	mi := &file_proto_apps_v0_comm_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommSubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommSubscribeRequest) ProtoMessage() {}

func (x *CommSubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_comm_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommSubscribeRequest.ProtoReflect.Descriptor instead.
func (*CommSubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_comm_proto_rawDescGZIP(), []int{8}
}

func (x *CommSubscribeRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type CommSubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommSubscribeResponse) Reset() {
	*x = CommSubscribeResponse{}
	mi := &file_proto_apps_v0_comm_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommSubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommSubscribeResponse) ProtoMessage() {}

func (x *CommSubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_comm_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommSubscribeResponse.ProtoReflect.Descriptor instead.
func (*CommSubscribeResponse) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_comm_proto_rawDescGZIP(), []int{9}
}

func (x *CommSubscribeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CommUnsubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommUnsubscribeRequest) Reset() {
	*x = CommUnsubscribeRequest{}
	mi := &file_proto_apps_v0_comm_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommUnsubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommUnsubscribeRequest) ProtoMessage() {}

func (x *CommUnsubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_comm_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommUnsubscribeRequest.ProtoReflect.Descriptor instead.
func (*CommUnsubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_comm_proto_rawDescGZIP(), []int{10}
}

func (x *CommUnsubscribeRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type CommUnsubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommUnsubscribeResponse) Reset() {
	*x = CommUnsubscribeResponse{}
	mi := &file_proto_apps_v0_comm_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommUnsubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommUnsubscribeResponse) ProtoMessage() {}

func (x *CommUnsubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_comm_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommUnsubscribeResponse.ProtoReflect.Descriptor instead.
func (*CommUnsubscribeResponse) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_comm_proto_rawDescGZIP(), []int{11}
}

func (x *CommUnsubscribeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CommRegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Capabilities  []string               `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommRegisterRequest) Reset() {
	*x = CommRegisterRequest{}
	mi := &file_proto_apps_v0_comm_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommRegisterRequest) ProtoMessage() {}

func (x *CommRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_comm_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommRegisterRequest.ProtoReflect.Descriptor instead.
func (*CommRegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_comm_proto_rawDescGZIP(), []int{12}
}

func (x *CommRegisterRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CommRegisterRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type CommRegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommRegisterResponse) Reset() {
	*x = CommRegisterResponse{}
	mi := &file_proto_apps_v0_comm_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommRegisterResponse) ProtoMessage() {}

func (x *CommRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_comm_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommRegisterResponse.ProtoReflect.Descriptor instead.
func (*CommRegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_comm_proto_rawDescGZIP(), []int{13}
}

func (x *CommRegisterResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CommDeregisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommDeregisterResponse) Reset() {
	*x = CommDeregisterResponse{}
	mi := &file_proto_apps_v0_comm_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommDeregisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommDeregisterResponse) ProtoMessage() {}

func (x *CommDeregisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_comm_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommDeregisterResponse.ProtoReflect.Descriptor instead.
func (*CommDeregisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_comm_proto_rawDescGZIP(), []int{14}
}

func (x *CommDeregisterResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// CommMessage is an inter-agent message.
type CommMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	From           string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To             string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Topic          string                 `protobuf:"bytes,4,opt,name=topic,proto3" json:"topic,omitempty"`
	ConversationId string                 `protobuf:"bytes,5,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Type           string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"` // "message", "mention", "proposal", "command", "info", "task", etc.
	Content        string                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp      int64                  `protobuf:"varint,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	HumanInjected  bool                   `protobuf:"varint,10,opt,name=human_injected,json=humanInjected,proto3" json:"human_injected,omitempty"`
	HumanId        string                 `protobuf:"bytes,11,opt,name=human_id,json=humanId,proto3" json:"human_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CommMessage) Reset() {
	*x = CommMessage{}
	mi := &file_proto_apps_v0_comm_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommMessage) ProtoMessage() {}

func (x *CommMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_comm_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommMessage.ProtoReflect.Descriptor instead.
func (*CommMessage) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_comm_proto_rawDescGZIP(), []int{15}
}

func (x *CommMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CommMessage) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *CommMessage) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *CommMessage) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *CommMessage) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *CommMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CommMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CommMessage) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CommMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *CommMessage) GetHumanInjected() bool {
	if x != nil {
		return x.HumanInjected
	}
	return false
}

func (x *CommMessage) GetHumanId() string {
	if x != nil {
		return x.HumanId
	}
	return ""
}

var File_proto_apps_v0_comm_proto protoreflect.FileDescriptor

const file_proto_apps_v0_comm_proto_rawDesc = "" +
	"\n" +
	"\x18proto/apps/v0/comm.proto\x12\aapps.v0\x1a\x1aproto/apps/v0/common.proto\"&\n" +
	"\x10CommNameResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"/\n" +
	"\x13CommVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"\x90\x01\n" +
	"\x12CommConnectRequest\x12?\n" +
	"\x06config\x18\x01 \x03(\v2'.apps.v0.CommConnectRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"+\n" +
	"\x13CommConnectResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\".\n" +
	"\x16CommDisconnectResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"7\n" +
	"\x17CommIsConnectedResponse\x12\x1c\n" +
	"\tconnected\x18\x01 \x01(\bR\tconnected\"A\n" +
	"\x0fCommSendRequest\x12.\n" +
	"\amessage\x18\x01 \x01(\v2\x14.apps.v0.CommMessageR\amessage\"(\n" +
	"\x10CommSendResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\",\n" +
	"\x14CommSubscribeRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\"-\n" +
	"\x15CommSubscribeResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\".\n" +
	"\x16CommUnsubscribeRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\"/\n" +
	"\x17CommUnsubscribeResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"T\n" +
	"\x13CommRegisterRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\"\n" +
	"\fcapabilities\x18\x02 \x03(\tR\fcapabilities\",\n" +
	"\x14CommRegisterResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\".\n" +
	"\x16CommDeregisterResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\x8b\x03\n" +
	"\vCommMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12\x14\n" +
	"\x05topic\x18\x04 \x01(\tR\x05topic\x12'\n" +
	"\x0fconversation_id\x18\x05 \x01(\tR\x0econversationId\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\x12>\n" +
	"\bmetadata\x18\b \x03(\v2\".apps.v0.CommMessage.MetadataEntryR\bmetadata\x12\x1c\n" +
	"\ttimestamp\x18\t \x01(\x03R\ttimestamp\x12%\n" +
	"\x0ehuman_injected\x18\n" +
	" \x01(\bR\rhumanInjected\x12\x19\n" +
	"\bhuman_id\x18\v \x01(\tR\ahumanId\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xd2\x06\n" +
	"\vCommService\x12H\n" +
	"\vHealthCheck\x12\x1b.apps.v0.HealthCheckRequest\x1a\x1c.apps.v0.HealthCheckResponse\x121\n" +
	"\x04Name\x12\x0e.apps.v0.Empty\x1a\x19.apps.v0.CommNameResponse\x127\n" +
	"\aVersion\x12\x0e.apps.v0.Empty\x1a\x1c.apps.v0.CommVersionResponse\x12D\n" +
	"\aConnect\x12\x1b.apps.v0.CommConnectRequest\x1a\x1c.apps.v0.CommConnectResponse\x12=\n" +
	"\n" +
	"Disconnect\x12\x0e.apps.v0.Empty\x1a\x1f.apps.v0.CommDisconnectResponse\x12?\n" +
	"\vIsConnected\x12\x0e.apps.v0.Empty\x1a .apps.v0.CommIsConnectedResponse\x12;\n" +
	"\x04Send\x12\x18.apps.v0.CommSendRequest\x1a\x19.apps.v0.CommSendResponse\x12J\n" +
	"\tSubscribe\x12\x1d.apps.v0.CommSubscribeRequest\x1a\x1e.apps.v0.CommSubscribeResponse\x12P\n" +
	"\vUnsubscribe\x12\x1f.apps.v0.CommUnsubscribeRequest\x1a .apps.v0.CommUnsubscribeResponse\x12G\n" +
	"\bRegister\x12\x1c.apps.v0.CommRegisterRequest\x1a\x1d.apps.v0.CommRegisterResponse\x12=\n" +
	"\n" +
	"Deregister\x12\x0e.apps.v0.Empty\x1a\x1f.apps.v0.CommDeregisterResponse\x121\n" +
	"\aReceive\x12\x0e.apps.v0.Empty\x1a\x14.apps.v0.CommMessage0\x01\x121\n" +
	"\tConfigure\x12\x14.apps.v0.SettingsMap\x1a\x0e.apps.v0.EmptyB$Z\"github.com/neboloop/nebo-sdk-go/pbb\x06proto3"

var (
	file_proto_apps_v0_comm_proto_rawDescOnce sync.Once
	file_proto_apps_v0_comm_proto_rawDescData []byte
)

func file_proto_apps_v0_comm_proto_rawDescGZIP() []byte {
	file_proto_apps_v0_comm_proto_rawDescOnce.Do(func() {
		file_proto_apps_v0_comm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_apps_v0_comm_proto_rawDesc), len(file_proto_apps_v0_comm_proto_rawDesc)))
	})
	return file_proto_apps_v0_comm_proto_rawDescData
}

var file_proto_apps_v0_comm_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_apps_v0_comm_proto_goTypes = []any{
	(*CommNameResponse)(nil),        // 0: apps.v0.CommNameResponse
	(*CommVersionResponse)(nil),     // 1: apps.v0.CommVersionResponse
	(*CommConnectRequest)(nil),      // 2: apps.v0.CommConnectRequest
	(*CommConnectResponse)(nil),     // 3: apps.v0.CommConnectResponse
	(*CommDisconnectResponse)(nil),  // 4: apps.v0.CommDisconnectResponse
	(*CommIsConnectedResponse)(nil), // 5: apps.v0.CommIsConnectedResponse
	(*CommSendRequest)(nil),         // 6: apps.v0.CommSendRequest
	(*CommSendResponse)(nil),        // 7: apps.v0.CommSendResponse
	(*CommSubscribeRequest)(nil),    // 8: apps.v0.CommSubscribeRequest
	(*CommSubscribeResponse)(nil),   // 9: apps.v0.CommSubscribeResponse
	(*CommUnsubscribeRequest)(nil),  // 10: apps.v0.CommUnsubscribeRequest
	(*CommUnsubscribeResponse)(nil), // 11: apps.v0.CommUnsubscribeResponse
	(*CommRegisterRequest)(nil),     // 12: apps.v0.CommRegisterRequest
	(*CommRegisterResponse)(nil),    // 13: apps.v0.CommRegisterResponse
	(*CommDeregisterResponse)(nil),  // 14: apps.v0.CommDeregisterResponse
	(*CommMessage)(nil),             // 15: apps.v0.CommMessage
	nil,                             // 16: apps.v0.CommConnectRequest.ConfigEntry
	nil,                             // 17: apps.v0.CommMessage.MetadataEntry
	(*HealthCheckRequest)(nil),      // 18: apps.v0.HealthCheckRequest
	(*Empty)(nil),                   // 19: apps.v0.Empty
	(*SettingsMap)(nil),             // 20: apps.v0.SettingsMap
	(*HealthCheckResponse)(nil),     // 21: apps.v0.HealthCheckResponse
}
var file_proto_apps_v0_comm_proto_depIdxs = []int32{
	16, // 0: apps.v0.CommConnectRequest.config:type_name -> apps.v0.CommConnectRequest.ConfigEntry
	15, // 1: apps.v0.CommSendRequest.message:type_name -> apps.v0.CommMessage
	17, // 2: apps.v0.CommMessage.metadata:type_name -> apps.v0.CommMessage.MetadataEntry
	18, // 3: apps.v0.CommService.HealthCheck:input_type -> apps.v0.HealthCheckRequest
	19, // 4: apps.v0.CommService.Name:input_type -> apps.v0.Empty
	19, // 5: apps.v0.CommService.Version:input_type -> apps.v0.Empty
	2,  // 6: apps.v0.CommService.Connect:input_type -> apps.v0.CommConnectRequest
	19, // 7: apps.v0.CommService.Disconnect:input_type -> apps.v0.Empty
	19, // 8: apps.v0.CommService.IsConnected:input_type -> apps.v0.Empty
	6,  // 9: apps.v0.CommService.Send:input_type -> apps.v0.CommSendRequest
	8,  // 10: apps.v0.CommService.Subscribe:input_type -> apps.v0.CommSubscribeRequest
	10, // 11: apps.v0.CommService.Unsubscribe:input_type -> apps.v0.CommUnsubscribeRequest
	12, // 12: apps.v0.CommService.Register:input_type -> apps.v0.CommRegisterRequest
	19, // 13: apps.v0.CommService.Deregister:input_type -> apps.v0.Empty
	19, // 14: apps.v0.CommService.Receive:input_type -> apps.v0.Empty
	20, // 15: apps.v0.CommService.Configure:input_type -> apps.v0.SettingsMap
	21, // 16: apps.v0.CommService.HealthCheck:output_type -> apps.v0.HealthCheckResponse
	0,  // 17: apps.v0.CommService.Name:output_type -> apps.v0.CommNameResponse
	1,  // 18: apps.v0.CommService.Version:output_type -> apps.v0.CommVersionResponse
	3,  // 19: apps.v0.CommService.Connect:output_type -> apps.v0.CommConnectResponse
	4,  // 20: apps.v0.CommService.Disconnect:output_type -> apps.v0.CommDisconnectResponse
	5,  // 21: apps.v0.CommService.IsConnected:output_type -> apps.v0.CommIsConnectedResponse
	7,  // 22: apps.v0.CommService.Send:output_type -> apps.v0.CommSendResponse
	9,  // 23: apps.v0.CommService.Subscribe:output_type -> apps.v0.CommSubscribeResponse
	11, // 24: apps.v0.CommService.Unsubscribe:output_type -> apps.v0.CommUnsubscribeResponse
	13, // 25: apps.v0.CommService.Register:output_type -> apps.v0.CommRegisterResponse
	14, // 26: apps.v0.CommService.Deregister:output_type -> apps.v0.CommDeregisterResponse
	15, // 27: apps.v0.CommService.Receive:output_type -> apps.v0.CommMessage
	19, // 28: apps.v0.CommService.Configure:output_type -> apps.v0.Empty
	16, // [16:29] is the sub-list for method output_type
	3,  // [3:16] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_apps_v0_comm_proto_init() }
func file_proto_apps_v0_comm_proto_init() {
	if File_proto_apps_v0_comm_proto != nil {
		return
	}
	file_proto_apps_v0_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_apps_v0_comm_proto_rawDesc), len(file_proto_apps_v0_comm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_apps_v0_comm_proto_goTypes,
		DependencyIndexes: file_proto_apps_v0_comm_proto_depIdxs,
		MessageInfos:      file_proto_apps_v0_comm_proto_msgTypes,
	}.Build()
	File_proto_apps_v0_comm_proto = out.File
	file_proto_apps_v0_comm_proto_goTypes = nil
	file_proto_apps_v0_comm_proto_depIdxs = nil
}
