// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.0
// source: proto/apps/v0/comm.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CommService_HealthCheck_FullMethodName = "/apps.v0.CommService/HealthCheck"
	CommService_Name_FullMethodName        = "/apps.v0.CommService/Name"
	CommService_Version_FullMethodName     = "/apps.v0.CommService/Version"
	CommService_Connect_FullMethodName     = "/apps.v0.CommService/Connect"
	CommService_Disconnect_FullMethodName  = "/apps.v0.CommService/Disconnect"
	CommService_IsConnected_FullMethodName = "/apps.v0.CommService/IsConnected"
	CommService_Send_FullMethodName        = "/apps.v0.CommService/Send"
	CommService_Subscribe_FullMethodName   = "/apps.v0.CommService/Subscribe"
	CommService_Unsubscribe_FullMethodName = "/apps.v0.CommService/Unsubscribe"
	CommService_Register_FullMethodName    = "/apps.v0.CommService/Register"
	CommService_Deregister_FullMethodName  = "/apps.v0.CommService/Deregister"
	CommService_Receive_FullMethodName     = "/apps.v0.CommService/Receive"
	CommService_Configure_FullMethodName   = "/apps.v0.CommService/Configure"
)

// CommServiceClient is the client API for CommService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CommService is the interface for inter-agent communication apps.
type CommServiceClient interface {
	// HealthCheck verifies the comm app is running.
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// Name returns the comm plugin's unique name.
	Name(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CommNameResponse, error)
	// Version returns the comm plugin's version.
	Version(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CommVersionResponse, error)
	// Connect establishes the communication link.
	Connect(ctx context.Context, in *CommConnectRequest, opts ...grpc.CallOption) (*CommConnectResponse, error)
	// Disconnect closes the communication link.
	Disconnect(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CommDisconnectResponse, error)
	// IsConnected checks if the link is active.
	IsConnected(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CommIsConnectedResponse, error)
	// Send sends a message to another agent.
	Send(ctx context.Context, in *CommSendRequest, opts ...grpc.CallOption) (*CommSendResponse, error)
	// Subscribe registers interest in a topic.
	Subscribe(ctx context.Context, in *CommSubscribeRequest, opts ...grpc.CallOption) (*CommSubscribeResponse, error)
	// Unsubscribe removes interest in a topic.
	Unsubscribe(ctx context.Context, in *CommUnsubscribeRequest, opts ...grpc.CallOption) (*CommUnsubscribeResponse, error)
	// Register announces this agent on the network.
	Register(ctx context.Context, in *CommRegisterRequest, opts ...grpc.CallOption) (*CommRegisterResponse, error)
	// Deregister removes this agent from the network.
	Deregister(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CommDeregisterResponse, error)
	// Receive streams inbound messages from the network to Nebo.
	Receive(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CommMessage], error)
	// Configure updates the app's settings.
	Configure(ctx context.Context, in *SettingsMap, opts ...grpc.CallOption) (*Empty, error)
}

type commServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCommServiceClient(cc grpc.ClientConnInterface) CommServiceClient {
	return &commServiceClient{cc}
}

func (c *commServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, CommService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commServiceClient) Name(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CommNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommNameResponse)
	err := c.cc.Invoke(ctx, CommService_Name_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commServiceClient) Version(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CommVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommVersionResponse)
	err := c.cc.Invoke(ctx, CommService_Version_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commServiceClient) Connect(ctx context.Context, in *CommConnectRequest, opts ...grpc.CallOption) (*CommConnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommConnectResponse)
	err := c.cc.Invoke(ctx, CommService_Connect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commServiceClient) Disconnect(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CommDisconnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommDisconnectResponse)
	err := c.cc.Invoke(ctx, CommService_Disconnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commServiceClient) IsConnected(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CommIsConnectedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommIsConnectedResponse)
	err := c.cc.Invoke(ctx, CommService_IsConnected_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commServiceClient) Send(ctx context.Context, in *CommSendRequest, opts ...grpc.CallOption) (*CommSendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommSendResponse)
	err := c.cc.Invoke(ctx, CommService_Send_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commServiceClient) Subscribe(ctx context.Context, in *CommSubscribeRequest, opts ...grpc.CallOption) (*CommSubscribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommSubscribeResponse)
	err := c.cc.Invoke(ctx, CommService_Subscribe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commServiceClient) Unsubscribe(ctx context.Context, in *CommUnsubscribeRequest, opts ...grpc.CallOption) (*CommUnsubscribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommUnsubscribeResponse)
	err := c.cc.Invoke(ctx, CommService_Unsubscribe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commServiceClient) Register(ctx context.Context, in *CommRegisterRequest, opts ...grpc.CallOption) (*CommRegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommRegisterResponse)
	err := c.cc.Invoke(ctx, CommService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commServiceClient) Deregister(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CommDeregisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommDeregisterResponse)
	err := c.cc.Invoke(ctx, CommService_Deregister_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commServiceClient) Receive(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CommMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CommService_ServiceDesc.Streams[0], CommService_Receive_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, CommMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CommService_ReceiveClient = grpc.ServerStreamingClient[CommMessage]

func (c *commServiceClient) Configure(ctx context.Context, in *SettingsMap, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, CommService_Configure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommServiceServer is the server API for CommService service.
// All implementations must embed UnimplementedCommServiceServer
// for forward compatibility.
//
// CommService is the interface for inter-agent communication apps.
type CommServiceServer interface {
	// HealthCheck verifies the comm app is running.
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// Name returns the comm plugin's unique name.
	Name(context.Context, *Empty) (*CommNameResponse, error)
	// Version returns the comm plugin's version.
	Version(context.Context, *Empty) (*CommVersionResponse, error)
	// Connect establishes the communication link.
	Connect(context.Context, *CommConnectRequest) (*CommConnectResponse, error)
	// Disconnect closes the communication link.
	Disconnect(context.Context, *Empty) (*CommDisconnectResponse, error)
	// IsConnected checks if the link is active.
	IsConnected(context.Context, *Empty) (*CommIsConnectedResponse, error)
	// Send sends a message to another agent.
	Send(context.Context, *CommSendRequest) (*CommSendResponse, error)
	// Subscribe registers interest in a topic.
	Subscribe(context.Context, *CommSubscribeRequest) (*CommSubscribeResponse, error)
	// Unsubscribe removes interest in a topic.
	Unsubscribe(context.Context, *CommUnsubscribeRequest) (*CommUnsubscribeResponse, error)
	// Register announces this agent on the network.
	Register(context.Context, *CommRegisterRequest) (*CommRegisterResponse, error)
	// Deregister removes this agent from the network.
	Deregister(context.Context, *Empty) (*CommDeregisterResponse, error)
	// Receive streams inbound messages from the network to Nebo.
	Receive(*Empty, grpc.ServerStreamingServer[CommMessage]) error
	// Configure updates the app's settings.
	Configure(context.Context, *SettingsMap) (*Empty, error)
	mustEmbedUnimplementedCommServiceServer()
}

// UnimplementedCommServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommServiceServer struct{}

func (UnimplementedCommServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedCommServiceServer) Name(context.Context, *Empty) (*CommNameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Name not implemented")
}
func (UnimplementedCommServiceServer) Version(context.Context, *Empty) (*CommVersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Version not implemented")
}
func (UnimplementedCommServiceServer) Connect(context.Context, *CommConnectRequest) (*CommConnectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedCommServiceServer) Disconnect(context.Context, *Empty) (*CommDisconnectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Disconnect not implemented")
}
func (UnimplementedCommServiceServer) IsConnected(context.Context, *Empty) (*CommIsConnectedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsConnected not implemented")
}
func (UnimplementedCommServiceServer) Send(context.Context, *CommSendRequest) (*CommSendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedCommServiceServer) Subscribe(context.Context, *CommSubscribeRequest) (*CommSubscribeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedCommServiceServer) Unsubscribe(context.Context, *CommUnsubscribeRequest) (*CommUnsubscribeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Unsubscribe not implemented")
}
func (UnimplementedCommServiceServer) Register(context.Context, *CommRegisterRequest) (*CommRegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedCommServiceServer) Deregister(context.Context, *Empty) (*CommDeregisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Deregister not implemented")
}
func (UnimplementedCommServiceServer) Receive(*Empty, grpc.ServerStreamingServer[CommMessage]) error {
	return status.Error(codes.Unimplemented, "method Receive not implemented")
}
func (UnimplementedCommServiceServer) Configure(context.Context, *SettingsMap) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Configure not implemented")
}
func (UnimplementedCommServiceServer) mustEmbedUnimplementedCommServiceServer() {}
func (UnimplementedCommServiceServer) testEmbeddedByValue()                     {}

// UnsafeCommServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommServiceServer will
// result in compilation errors.
type UnsafeCommServiceServer interface {
	mustEmbedUnimplementedCommServiceServer()
}

func RegisterCommServiceServer(s grpc.ServiceRegistrar, srv CommServiceServer) {
	// If the following call panics, it indicates UnimplementedCommServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CommService_ServiceDesc, srv)
}

func _CommService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommService_Name_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommServiceServer).Name(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommService_Name_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommServiceServer).Name(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommService_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommServiceServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommService_Version_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommServiceServer).Version(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommService_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommServiceServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommService_Connect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommServiceServer).Connect(ctx, req.(*CommConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommService_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommServiceServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommService_Disconnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommServiceServer).Disconnect(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommService_IsConnected_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommServiceServer).IsConnected(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommService_IsConnected_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommServiceServer).IsConnected(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommService_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommSendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommServiceServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommService_Send_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommServiceServer).Send(ctx, req.(*CommSendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommService_Subscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommSubscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommServiceServer).Subscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommService_Subscribe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommServiceServer).Subscribe(ctx, req.(*CommSubscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommService_Unsubscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommUnsubscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommServiceServer).Unsubscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommService_Unsubscribe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommServiceServer).Unsubscribe(ctx, req.(*CommUnsubscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommServiceServer).Register(ctx, req.(*CommRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommService_Deregister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommServiceServer).Deregister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommService_Deregister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommServiceServer).Deregister(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommService_Receive_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CommServiceServer).Receive(m, &grpc.GenericServerStream[Empty, CommMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CommService_ReceiveServer = grpc.ServerStreamingServer[CommMessage]

func _CommService_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettingsMap)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommServiceServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommService_Configure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommServiceServer).Configure(ctx, req.(*SettingsMap))
	}
	return interceptor(ctx, in, info, handler)
}

// CommService_ServiceDesc is the grpc.ServiceDesc for CommService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "apps.v0.CommService",
	HandlerType: (*CommServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _CommService_HealthCheck_Handler,
		},
		{
			MethodName: "Name",
			Handler:    _CommService_Name_Handler,
		},
		{
			MethodName: "Version",
			Handler:    _CommService_Version_Handler,
		},
		{
			MethodName: "Connect",
			Handler:    _CommService_Connect_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _CommService_Disconnect_Handler,
		},
		{
			MethodName: "IsConnected",
			Handler:    _CommService_IsConnected_Handler,
		},
		{
			MethodName: "Send",
			Handler:    _CommService_Send_Handler,
		},
		{
			MethodName: "Subscribe",
			Handler:    _CommService_Subscribe_Handler,
		},
		{
			MethodName: "Unsubscribe",
			Handler:    _CommService_Unsubscribe_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _CommService_Register_Handler,
		},
		{
			MethodName: "Deregister",
			Handler:    _CommService_Deregister_Handler,
		},
		{
			MethodName: "Configure",
			Handler:    _CommService_Configure_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Receive",
			Handler:       _CommService_Receive_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/apps/v0/comm.proto",
}
