// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.4
// source: proto/apps/v0/gateway.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GatewayRequest is sent by Nebo to start a chat completion.
// No model field — the gateway decides routing.
type GatewayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Messages      []*GatewayMessage      `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	Tools         []*GatewayToolDef      `protobuf:"bytes,3,rep,name=tools,proto3" json:"tools,omitempty"`
	MaxTokens     int32                  `protobuf:"varint,4,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	Temperature   float64                `protobuf:"fixed64,5,opt,name=temperature,proto3" json:"temperature,omitempty"`
	System        string                 `protobuf:"bytes,6,opt,name=system,proto3" json:"system,omitempty"`
	User          *UserContext           `protobuf:"bytes,7,opt,name=user,proto3" json:"user,omitempty"` // Per-request user identity (JWT, user_id, plan)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayRequest) Reset() {
	*x = GatewayRequest{}
	mi := &file_proto_apps_v0_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayRequest) ProtoMessage() {}

func (x *GatewayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayRequest.ProtoReflect.Descriptor instead.
func (*GatewayRequest) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *GatewayRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GatewayRequest) GetMessages() []*GatewayMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *GatewayRequest) GetTools() []*GatewayToolDef {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *GatewayRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *GatewayRequest) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *GatewayRequest) GetSystem() string {
	if x != nil {
		return x.System
	}
	return ""
}

func (x *GatewayRequest) GetUser() *UserContext {
	if x != nil {
		return x.User
	}
	return nil
}

// GatewayMessage represents a single message in the conversation.
type GatewayMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`                                 // "user", "assistant", "tool"
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                           // Text content
	ToolCallId    string                 `protobuf:"bytes,3,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"` // For role="tool": which tool call this responds to
	ToolCalls     string                 `protobuf:"bytes,4,opt,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`      // For role="assistant": JSON-encoded array of tool calls
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayMessage) Reset() {
	*x = GatewayMessage{}
	mi := &file_proto_apps_v0_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayMessage) ProtoMessage() {}

func (x *GatewayMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayMessage.ProtoReflect.Descriptor instead.
func (*GatewayMessage) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *GatewayMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *GatewayMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GatewayMessage) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *GatewayMessage) GetToolCalls() string {
	if x != nil {
		return x.ToolCalls
	}
	return ""
}

// GatewayToolDef describes a tool available to the model.
type GatewayToolDef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	InputSchema   []byte                 `protobuf:"bytes,3,opt,name=input_schema,json=inputSchema,proto3" json:"input_schema,omitempty"` // JSON Schema for tool input
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayToolDef) Reset() {
	*x = GatewayToolDef{}
	mi := &file_proto_apps_v0_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayToolDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayToolDef) ProtoMessage() {}

func (x *GatewayToolDef) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayToolDef.ProtoReflect.Descriptor instead.
func (*GatewayToolDef) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *GatewayToolDef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GatewayToolDef) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GatewayToolDef) GetInputSchema() []byte {
	if x != nil {
		return x.InputSchema
	}
	return nil
}

// GatewayEvent is a streamed event from the gateway.
type GatewayEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`                            // "text", "tool_call", "thinking", "error", "done"
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                      // Text chunk, or JSON blob for tool_call: {"id","name","arguments"}
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`                          // Informational: which model actually handled the request
	RequestId     string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // Correlates to the originating GatewayRequest
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayEvent) Reset() {
	*x = GatewayEvent{}
	mi := &file_proto_apps_v0_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayEvent) ProtoMessage() {}

func (x *GatewayEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayEvent.ProtoReflect.Descriptor instead.
func (*GatewayEvent) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *GatewayEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GatewayEvent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GatewayEvent) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GatewayEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// PollRequest asks for buffered events from an active stream.
type PollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollRequest) Reset() {
	*x = PollRequest{}
	mi := &file_proto_apps_v0_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollRequest) ProtoMessage() {}

func (x *PollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollRequest.ProtoReflect.Descriptor instead.
func (*PollRequest) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *PollRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// PollResponse returns buffered events.
type PollResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*GatewayEvent        `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	Complete      bool                   `protobuf:"varint,2,opt,name=complete,proto3" json:"complete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollResponse) Reset() {
	*x = PollResponse{}
	mi := &file_proto_apps_v0_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollResponse) ProtoMessage() {}

func (x *PollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollResponse.ProtoReflect.Descriptor instead.
func (*PollResponse) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *PollResponse) GetEvents() []*GatewayEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *PollResponse) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

// CancelRequest aborts an active stream.
type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_proto_apps_v0_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *CancelRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// CancelResponse confirms cancellation.
type CancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cancelled     bool                   `protobuf:"varint,1,opt,name=cancelled,proto3" json:"cancelled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResponse) Reset() {
	*x = CancelResponse{}
	mi := &file_proto_apps_v0_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResponse) ProtoMessage() {}

func (x *CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResponse.ProtoReflect.Descriptor instead.
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *CancelResponse) GetCancelled() bool {
	if x != nil {
		return x.Cancelled
	}
	return false
}

var File_proto_apps_v0_gateway_proto protoreflect.FileDescriptor

const file_proto_apps_v0_gateway_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/apps/v0/gateway.proto\x12\aapps.v0\x1a\x1aproto/apps/v0/common.proto\"\x96\x02\n" +
	"\x0eGatewayRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x123\n" +
	"\bmessages\x18\x02 \x03(\v2\x17.apps.v0.GatewayMessageR\bmessages\x12-\n" +
	"\x05tools\x18\x03 \x03(\v2\x17.apps.v0.GatewayToolDefR\x05tools\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x04 \x01(\x05R\tmaxTokens\x12 \n" +
	"\vtemperature\x18\x05 \x01(\x01R\vtemperature\x12\x16\n" +
	"\x06system\x18\x06 \x01(\tR\x06system\x12(\n" +
	"\x04user\x18\a \x01(\v2\x14.apps.v0.UserContextR\x04user\"\x7f\n" +
	"\x0eGatewayMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12 \n" +
	"\ftool_call_id\x18\x03 \x01(\tR\n" +
	"toolCallId\x12\x1d\n" +
	"\n" +
	"tool_calls\x18\x04 \x01(\tR\ttoolCalls\"i\n" +
	"\x0eGatewayToolDef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12!\n" +
	"\finput_schema\x18\x03 \x01(\fR\vinputSchema\"q\n" +
	"\fGatewayEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\",\n" +
	"\vPollRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"Y\n" +
	"\fPollResponse\x12-\n" +
	"\x06events\x18\x01 \x03(\v2\x15.apps.v0.GatewayEventR\x06events\x12\x1a\n" +
	"\bcomplete\x18\x02 \x01(\bR\bcomplete\".\n" +
	"\rCancelRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\".\n" +
	"\x0eCancelResponse\x12\x1c\n" +
	"\tcancelled\x18\x01 \x01(\bR\tcancelled2\xb9\x02\n" +
	"\x0eGatewayService\x12H\n" +
	"\vHealthCheck\x12\x1b.apps.v0.HealthCheckRequest\x1a\x1c.apps.v0.HealthCheckResponse\x12:\n" +
	"\x06Stream\x12\x17.apps.v0.GatewayRequest\x1a\x15.apps.v0.GatewayEvent0\x01\x123\n" +
	"\x04Poll\x12\x14.apps.v0.PollRequest\x1a\x15.apps.v0.PollResponse\x129\n" +
	"\x06Cancel\x12\x16.apps.v0.CancelRequest\x1a\x17.apps.v0.CancelResponse\x121\n" +
	"\tConfigure\x12\x14.apps.v0.SettingsMap\x1a\x0e.apps.v0.EmptyB$Z\"github.com/neboloop/nebo-sdk-go/pbb\x06proto3"

var (
	file_proto_apps_v0_gateway_proto_rawDescOnce sync.Once
	file_proto_apps_v0_gateway_proto_rawDescData []byte
)

func file_proto_apps_v0_gateway_proto_rawDescGZIP() []byte {
	file_proto_apps_v0_gateway_proto_rawDescOnce.Do(func() {
		file_proto_apps_v0_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_apps_v0_gateway_proto_rawDesc), len(file_proto_apps_v0_gateway_proto_rawDesc)))
	})
	return file_proto_apps_v0_gateway_proto_rawDescData
}

var file_proto_apps_v0_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_apps_v0_gateway_proto_goTypes = []any{
	(*GatewayRequest)(nil),      // 0: apps.v0.GatewayRequest
	(*GatewayMessage)(nil),      // 1: apps.v0.GatewayMessage
	(*GatewayToolDef)(nil),      // 2: apps.v0.GatewayToolDef
	(*GatewayEvent)(nil),        // 3: apps.v0.GatewayEvent
	(*PollRequest)(nil),         // 4: apps.v0.PollRequest
	(*PollResponse)(nil),        // 5: apps.v0.PollResponse
	(*CancelRequest)(nil),       // 6: apps.v0.CancelRequest
	(*CancelResponse)(nil),      // 7: apps.v0.CancelResponse
	(*UserContext)(nil),         // 8: apps.v0.UserContext
	(*HealthCheckRequest)(nil),  // 9: apps.v0.HealthCheckRequest
	(*SettingsMap)(nil),         // 10: apps.v0.SettingsMap
	(*HealthCheckResponse)(nil), // 11: apps.v0.HealthCheckResponse
	(*Empty)(nil),               // 12: apps.v0.Empty
}
var file_proto_apps_v0_gateway_proto_depIdxs = []int32{
	1,  // 0: apps.v0.GatewayRequest.messages:type_name -> apps.v0.GatewayMessage
	2,  // 1: apps.v0.GatewayRequest.tools:type_name -> apps.v0.GatewayToolDef
	8,  // 2: apps.v0.GatewayRequest.user:type_name -> apps.v0.UserContext
	3,  // 3: apps.v0.PollResponse.events:type_name -> apps.v0.GatewayEvent
	9,  // 4: apps.v0.GatewayService.HealthCheck:input_type -> apps.v0.HealthCheckRequest
	0,  // 5: apps.v0.GatewayService.Stream:input_type -> apps.v0.GatewayRequest
	4,  // 6: apps.v0.GatewayService.Poll:input_type -> apps.v0.PollRequest
	6,  // 7: apps.v0.GatewayService.Cancel:input_type -> apps.v0.CancelRequest
	10, // 8: apps.v0.GatewayService.Configure:input_type -> apps.v0.SettingsMap
	11, // 9: apps.v0.GatewayService.HealthCheck:output_type -> apps.v0.HealthCheckResponse
	3,  // 10: apps.v0.GatewayService.Stream:output_type -> apps.v0.GatewayEvent
	5,  // 11: apps.v0.GatewayService.Poll:output_type -> apps.v0.PollResponse
	7,  // 12: apps.v0.GatewayService.Cancel:output_type -> apps.v0.CancelResponse
	12, // 13: apps.v0.GatewayService.Configure:output_type -> apps.v0.Empty
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_apps_v0_gateway_proto_init() }
func file_proto_apps_v0_gateway_proto_init() {
	if File_proto_apps_v0_gateway_proto != nil {
		return
	}
	file_proto_apps_v0_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_apps_v0_gateway_proto_rawDesc), len(file_proto_apps_v0_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_apps_v0_gateway_proto_goTypes,
		DependencyIndexes: file_proto_apps_v0_gateway_proto_depIdxs,
		MessageInfos:      file_proto_apps_v0_gateway_proto_msgTypes,
	}.Build()
	File_proto_apps_v0_gateway_proto = out.File
	file_proto_apps_v0_gateway_proto_goTypes = nil
	file_proto_apps_v0_gateway_proto_depIdxs = nil
}
