// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.4
// source: proto/apps/v0/schedule.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Schedule represents a single scheduled task.
type Schedule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Expression    string                 `protobuf:"bytes,3,opt,name=expression,proto3" json:"expression,omitempty"`             // Cron expression (6-field with seconds)
	TaskType      string                 `protobuf:"bytes,4,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"` // "bash" or "agent"
	Command       string                 `protobuf:"bytes,5,opt,name=command,proto3" json:"command,omitempty"`                   // Shell command (for bash tasks)
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`                   // Agent prompt (for agent tasks)
	Deliver       string                 `protobuf:"bytes,7,opt,name=deliver,proto3" json:"deliver,omitempty"`                   // JSON: {"channel":"telegram","to":"123"}
	Enabled       bool                   `protobuf:"varint,8,opt,name=enabled,proto3" json:"enabled,omitempty"`
	LastRun       string                 `protobuf:"bytes,9,opt,name=last_run,json=lastRun,proto3" json:"last_run,omitempty"`  // RFC3339 timestamp
	NextRun       string                 `protobuf:"bytes,10,opt,name=next_run,json=nextRun,proto3" json:"next_run,omitempty"` // RFC3339 timestamp
	RunCount      int64                  `protobuf:"varint,11,opt,name=run_count,json=runCount,proto3" json:"run_count,omitempty"`
	LastError     string                 `protobuf:"bytes,12,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // RFC3339 timestamp
	Metadata      map[string]string      `protobuf:"bytes,14,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schedule) Reset() {
	*x = Schedule{}
	mi := &file_proto_apps_v0_schedule_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schedule) ProtoMessage() {}

func (x *Schedule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_schedule_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schedule.ProtoReflect.Descriptor instead.
func (*Schedule) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_schedule_proto_rawDescGZIP(), []int{0}
}

func (x *Schedule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Schedule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Schedule) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

func (x *Schedule) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *Schedule) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Schedule) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Schedule) GetDeliver() string {
	if x != nil {
		return x.Deliver
	}
	return ""
}

func (x *Schedule) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Schedule) GetLastRun() string {
	if x != nil {
		return x.LastRun
	}
	return ""
}

func (x *Schedule) GetNextRun() string {
	if x != nil {
		return x.NextRun
	}
	return ""
}

func (x *Schedule) GetRunCount() int64 {
	if x != nil {
		return x.RunCount
	}
	return 0
}

func (x *Schedule) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *Schedule) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Schedule) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ScheduleTrigger is emitted by the app when a schedule fires.
// Denormalized so Nebo can route without an extra lookup.
type ScheduleTrigger struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScheduleId    string                 `protobuf:"bytes,1,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TaskType      string                 `protobuf:"bytes,3,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	Command       string                 `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Deliver       string                 `protobuf:"bytes,6,opt,name=deliver,proto3" json:"deliver,omitempty"`
	FiredAt       string                 `protobuf:"bytes,7,opt,name=fired_at,json=firedAt,proto3" json:"fired_at,omitempty"` // RFC3339 timestamp
	Metadata      map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleTrigger) Reset() {
	*x = ScheduleTrigger{}
	mi := &file_proto_apps_v0_schedule_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleTrigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleTrigger) ProtoMessage() {}

func (x *ScheduleTrigger) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_schedule_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleTrigger.ProtoReflect.Descriptor instead.
func (*ScheduleTrigger) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_schedule_proto_rawDescGZIP(), []int{1}
}

func (x *ScheduleTrigger) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

func (x *ScheduleTrigger) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ScheduleTrigger) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *ScheduleTrigger) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ScheduleTrigger) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ScheduleTrigger) GetDeliver() string {
	if x != nil {
		return x.Deliver
	}
	return ""
}

func (x *ScheduleTrigger) GetFiredAt() string {
	if x != nil {
		return x.FiredAt
	}
	return ""
}

func (x *ScheduleTrigger) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CreateScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Expression    string                 `protobuf:"bytes,2,opt,name=expression,proto3" json:"expression,omitempty"`
	TaskType      string                 `protobuf:"bytes,3,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	Command       string                 `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Deliver       string                 `protobuf:"bytes,6,opt,name=deliver,proto3" json:"deliver,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateScheduleRequest) Reset() {
	*x = CreateScheduleRequest{}
	mi := &file_proto_apps_v0_schedule_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScheduleRequest) ProtoMessage() {}

func (x *CreateScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_schedule_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScheduleRequest.ProtoReflect.Descriptor instead.
func (*CreateScheduleRequest) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_schedule_proto_rawDescGZIP(), []int{2}
}

func (x *CreateScheduleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateScheduleRequest) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

func (x *CreateScheduleRequest) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *CreateScheduleRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CreateScheduleRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateScheduleRequest) GetDeliver() string {
	if x != nil {
		return x.Deliver
	}
	return ""
}

func (x *CreateScheduleRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScheduleRequest) Reset() {
	*x = GetScheduleRequest{}
	mi := &file_proto_apps_v0_schedule_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScheduleRequest) ProtoMessage() {}

func (x *GetScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_schedule_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScheduleRequest.ProtoReflect.Descriptor instead.
func (*GetScheduleRequest) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_schedule_proto_rawDescGZIP(), []int{3}
}

func (x *GetScheduleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListSchedulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	EnabledOnly   bool                   `protobuf:"varint,3,opt,name=enabled_only,json=enabledOnly,proto3" json:"enabled_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSchedulesRequest) Reset() {
	*x = ListSchedulesRequest{}
	mi := &file_proto_apps_v0_schedule_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSchedulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSchedulesRequest) ProtoMessage() {}

func (x *ListSchedulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_schedule_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSchedulesRequest.ProtoReflect.Descriptor instead.
func (*ListSchedulesRequest) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_schedule_proto_rawDescGZIP(), []int{4}
}

func (x *ListSchedulesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListSchedulesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListSchedulesRequest) GetEnabledOnly() bool {
	if x != nil {
		return x.EnabledOnly
	}
	return false
}

type ListSchedulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schedules     []*Schedule            `protobuf:"bytes,1,rep,name=schedules,proto3" json:"schedules,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSchedulesResponse) Reset() {
	*x = ListSchedulesResponse{}
	mi := &file_proto_apps_v0_schedule_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSchedulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSchedulesResponse) ProtoMessage() {}

func (x *ListSchedulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_schedule_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSchedulesResponse.ProtoReflect.Descriptor instead.
func (*ListSchedulesResponse) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_schedule_proto_rawDescGZIP(), []int{5}
}

func (x *ListSchedulesResponse) GetSchedules() []*Schedule {
	if x != nil {
		return x.Schedules
	}
	return nil
}

func (x *ListSchedulesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdateScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Expression    string                 `protobuf:"bytes,2,opt,name=expression,proto3" json:"expression,omitempty"`
	TaskType      string                 `protobuf:"bytes,3,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	Command       string                 `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Deliver       string                 `protobuf:"bytes,6,opt,name=deliver,proto3" json:"deliver,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateScheduleRequest) Reset() {
	*x = UpdateScheduleRequest{}
	mi := &file_proto_apps_v0_schedule_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateScheduleRequest) ProtoMessage() {}

func (x *UpdateScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_schedule_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateScheduleRequest.ProtoReflect.Descriptor instead.
func (*UpdateScheduleRequest) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_schedule_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateScheduleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateScheduleRequest) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

func (x *UpdateScheduleRequest) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *UpdateScheduleRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *UpdateScheduleRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateScheduleRequest) GetDeliver() string {
	if x != nil {
		return x.Deliver
	}
	return ""
}

func (x *UpdateScheduleRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schedule      *Schedule              `protobuf:"bytes,1,opt,name=schedule,proto3" json:"schedule,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleResponse) Reset() {
	*x = ScheduleResponse{}
	mi := &file_proto_apps_v0_schedule_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleResponse) ProtoMessage() {}

func (x *ScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_schedule_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleResponse.ProtoReflect.Descriptor instead.
func (*ScheduleResponse) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_schedule_proto_rawDescGZIP(), []int{7}
}

func (x *ScheduleResponse) GetSchedule() *Schedule {
	if x != nil {
		return x.Schedule
	}
	return nil
}

func (x *ScheduleResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteScheduleRequest) Reset() {
	*x = DeleteScheduleRequest{}
	mi := &file_proto_apps_v0_schedule_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteScheduleRequest) ProtoMessage() {}

func (x *DeleteScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_schedule_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteScheduleRequest.ProtoReflect.Descriptor instead.
func (*DeleteScheduleRequest) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_schedule_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteScheduleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteScheduleResponse) Reset() {
	*x = DeleteScheduleResponse{}
	mi := &file_proto_apps_v0_schedule_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteScheduleResponse) ProtoMessage() {}

func (x *DeleteScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_schedule_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteScheduleResponse.ProtoReflect.Descriptor instead.
func (*DeleteScheduleResponse) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_schedule_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteScheduleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteScheduleResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ScheduleNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleNameRequest) Reset() {
	*x = ScheduleNameRequest{}
	mi := &file_proto_apps_v0_schedule_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleNameRequest) ProtoMessage() {}

func (x *ScheduleNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_schedule_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleNameRequest.ProtoReflect.Descriptor instead.
func (*ScheduleNameRequest) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_schedule_proto_rawDescGZIP(), []int{10}
}

func (x *ScheduleNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type TriggerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerResponse) Reset() {
	*x = TriggerResponse{}
	mi := &file_proto_apps_v0_schedule_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerResponse) ProtoMessage() {}

func (x *TriggerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_schedule_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerResponse.ProtoReflect.Descriptor instead.
func (*TriggerResponse) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_schedule_proto_rawDescGZIP(), []int{11}
}

func (x *TriggerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TriggerResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *TriggerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ScheduleHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleHistoryRequest) Reset() {
	*x = ScheduleHistoryRequest{}
	mi := &file_proto_apps_v0_schedule_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleHistoryRequest) ProtoMessage() {}

func (x *ScheduleHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_schedule_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleHistoryRequest.ProtoReflect.Descriptor instead.
func (*ScheduleHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_schedule_proto_rawDescGZIP(), []int{12}
}

func (x *ScheduleHistoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ScheduleHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ScheduleHistoryRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ScheduleHistoryResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Entries       []*ScheduleHistoryEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Total         int64                   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleHistoryResponse) Reset() {
	*x = ScheduleHistoryResponse{}
	mi := &file_proto_apps_v0_schedule_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleHistoryResponse) ProtoMessage() {}

func (x *ScheduleHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_schedule_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleHistoryResponse.ProtoReflect.Descriptor instead.
func (*ScheduleHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_schedule_proto_rawDescGZIP(), []int{13}
}

func (x *ScheduleHistoryResponse) GetEntries() []*ScheduleHistoryEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ScheduleHistoryResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ScheduleHistoryEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ScheduleName  string                 `protobuf:"bytes,2,opt,name=schedule_name,json=scheduleName,proto3" json:"schedule_name,omitempty"`
	StartedAt     string                 `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`    // RFC3339
	FinishedAt    string                 `protobuf:"bytes,4,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"` // RFC3339
	Success       bool                   `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	Output        string                 `protobuf:"bytes,6,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleHistoryEntry) Reset() {
	*x = ScheduleHistoryEntry{}
	mi := &file_proto_apps_v0_schedule_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleHistoryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleHistoryEntry) ProtoMessage() {}

func (x *ScheduleHistoryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_schedule_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleHistoryEntry.ProtoReflect.Descriptor instead.
func (*ScheduleHistoryEntry) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_schedule_proto_rawDescGZIP(), []int{14}
}

func (x *ScheduleHistoryEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ScheduleHistoryEntry) GetScheduleName() string {
	if x != nil {
		return x.ScheduleName
	}
	return ""
}

func (x *ScheduleHistoryEntry) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *ScheduleHistoryEntry) GetFinishedAt() string {
	if x != nil {
		return x.FinishedAt
	}
	return ""
}

func (x *ScheduleHistoryEntry) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ScheduleHistoryEntry) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ScheduleHistoryEntry) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_apps_v0_schedule_proto protoreflect.FileDescriptor

const file_proto_apps_v0_schedule_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/apps/v0/schedule.proto\x12\aapps.v0\x1a\x1aproto/apps/v0/common.proto\"\xde\x03\n" +
	"\bSchedule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"expression\x18\x03 \x01(\tR\n" +
	"expression\x12\x1b\n" +
	"\ttask_type\x18\x04 \x01(\tR\btaskType\x12\x18\n" +
	"\acommand\x18\x05 \x01(\tR\acommand\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x12\x18\n" +
	"\adeliver\x18\a \x01(\tR\adeliver\x12\x18\n" +
	"\aenabled\x18\b \x01(\bR\aenabled\x12\x19\n" +
	"\blast_run\x18\t \x01(\tR\alastRun\x12\x19\n" +
	"\bnext_run\x18\n" +
	" \x01(\tR\anextRun\x12\x1b\n" +
	"\trun_count\x18\v \x01(\x03R\brunCount\x12\x1d\n" +
	"\n" +
	"last_error\x18\f \x01(\tR\tlastError\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\tR\tcreatedAt\x12;\n" +
	"\bmetadata\x18\x0e \x03(\v2\x1f.apps.v0.Schedule.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcd\x02\n" +
	"\x0fScheduleTrigger\x12\x1f\n" +
	"\vschedule_id\x18\x01 \x01(\tR\n" +
	"scheduleId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\ttask_type\x18\x03 \x01(\tR\btaskType\x12\x18\n" +
	"\acommand\x18\x04 \x01(\tR\acommand\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x18\n" +
	"\adeliver\x18\x06 \x01(\tR\adeliver\x12\x19\n" +
	"\bfired_at\x18\a \x01(\tR\afiredAt\x12B\n" +
	"\bmetadata\x18\b \x03(\v2&.apps.v0.ScheduleTrigger.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbd\x02\n" +
	"\x15CreateScheduleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"expression\x18\x02 \x01(\tR\n" +
	"expression\x12\x1b\n" +
	"\ttask_type\x18\x03 \x01(\tR\btaskType\x12\x18\n" +
	"\acommand\x18\x04 \x01(\tR\acommand\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x18\n" +
	"\adeliver\x18\x06 \x01(\tR\adeliver\x12H\n" +
	"\bmetadata\x18\a \x03(\v2,.apps.v0.CreateScheduleRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"(\n" +
	"\x12GetScheduleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"g\n" +
	"\x14ListSchedulesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12!\n" +
	"\fenabled_only\x18\x03 \x01(\bR\venabledOnly\"^\n" +
	"\x15ListSchedulesResponse\x12/\n" +
	"\tschedules\x18\x01 \x03(\v2\x11.apps.v0.ScheduleR\tschedules\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xbd\x02\n" +
	"\x15UpdateScheduleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"expression\x18\x02 \x01(\tR\n" +
	"expression\x12\x1b\n" +
	"\ttask_type\x18\x03 \x01(\tR\btaskType\x12\x18\n" +
	"\acommand\x18\x04 \x01(\tR\acommand\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x18\n" +
	"\adeliver\x18\x06 \x01(\tR\adeliver\x12H\n" +
	"\bmetadata\x18\a \x03(\v2,.apps.v0.UpdateScheduleRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"W\n" +
	"\x10ScheduleResponse\x12-\n" +
	"\bschedule\x18\x01 \x01(\v2\x11.apps.v0.ScheduleR\bschedule\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"+\n" +
	"\x15DeleteScheduleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"H\n" +
	"\x16DeleteScheduleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\")\n" +
	"\x13ScheduleNameRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"Y\n" +
	"\x0fTriggerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"Z\n" +
	"\x16ScheduleHistoryRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"h\n" +
	"\x17ScheduleHistoryResponse\x127\n" +
	"\aentries\x18\x01 \x03(\v2\x1d.apps.v0.ScheduleHistoryEntryR\aentries\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xd3\x01\n" +
	"\x14ScheduleHistoryEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rschedule_name\x18\x02 \x01(\tR\fscheduleName\x12\x1d\n" +
	"\n" +
	"started_at\x18\x03 \x01(\tR\tstartedAt\x12\x1f\n" +
	"\vfinished_at\x18\x04 \x01(\tR\n" +
	"finishedAt\x12\x18\n" +
	"\asuccess\x18\x05 \x01(\bR\asuccess\x12\x16\n" +
	"\x06output\x18\x06 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error2\xb9\x06\n" +
	"\x0fScheduleService\x12H\n" +
	"\vHealthCheck\x12\x1b.apps.v0.HealthCheckRequest\x1a\x1c.apps.v0.HealthCheckResponse\x12C\n" +
	"\x06Create\x12\x1e.apps.v0.CreateScheduleRequest\x1a\x19.apps.v0.ScheduleResponse\x12=\n" +
	"\x03Get\x12\x1b.apps.v0.GetScheduleRequest\x1a\x19.apps.v0.ScheduleResponse\x12E\n" +
	"\x04List\x12\x1d.apps.v0.ListSchedulesRequest\x1a\x1e.apps.v0.ListSchedulesResponse\x12C\n" +
	"\x06Update\x12\x1e.apps.v0.UpdateScheduleRequest\x1a\x19.apps.v0.ScheduleResponse\x12I\n" +
	"\x06Delete\x12\x1e.apps.v0.DeleteScheduleRequest\x1a\x1f.apps.v0.DeleteScheduleResponse\x12A\n" +
	"\x06Enable\x12\x1c.apps.v0.ScheduleNameRequest\x1a\x19.apps.v0.ScheduleResponse\x12B\n" +
	"\aDisable\x12\x1c.apps.v0.ScheduleNameRequest\x1a\x19.apps.v0.ScheduleResponse\x12A\n" +
	"\aTrigger\x12\x1c.apps.v0.ScheduleNameRequest\x1a\x18.apps.v0.TriggerResponse\x12L\n" +
	"\aHistory\x12\x1f.apps.v0.ScheduleHistoryRequest\x1a .apps.v0.ScheduleHistoryResponse\x126\n" +
	"\bTriggers\x12\x0e.apps.v0.Empty\x1a\x18.apps.v0.ScheduleTrigger0\x01\x121\n" +
	"\tConfigure\x12\x14.apps.v0.SettingsMap\x1a\x0e.apps.v0.EmptyB$Z\"github.com/neboloop/nebo-sdk-go/pbb\x06proto3"

var (
	file_proto_apps_v0_schedule_proto_rawDescOnce sync.Once
	file_proto_apps_v0_schedule_proto_rawDescData []byte
)

func file_proto_apps_v0_schedule_proto_rawDescGZIP() []byte {
	file_proto_apps_v0_schedule_proto_rawDescOnce.Do(func() {
		file_proto_apps_v0_schedule_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_apps_v0_schedule_proto_rawDesc), len(file_proto_apps_v0_schedule_proto_rawDesc)))
	})
	return file_proto_apps_v0_schedule_proto_rawDescData
}

var file_proto_apps_v0_schedule_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_apps_v0_schedule_proto_goTypes = []any{
	(*Schedule)(nil),                // 0: apps.v0.Schedule
	(*ScheduleTrigger)(nil),         // 1: apps.v0.ScheduleTrigger
	(*CreateScheduleRequest)(nil),   // 2: apps.v0.CreateScheduleRequest
	(*GetScheduleRequest)(nil),      // 3: apps.v0.GetScheduleRequest
	(*ListSchedulesRequest)(nil),    // 4: apps.v0.ListSchedulesRequest
	(*ListSchedulesResponse)(nil),   // 5: apps.v0.ListSchedulesResponse
	(*UpdateScheduleRequest)(nil),   // 6: apps.v0.UpdateScheduleRequest
	(*ScheduleResponse)(nil),        // 7: apps.v0.ScheduleResponse
	(*DeleteScheduleRequest)(nil),   // 8: apps.v0.DeleteScheduleRequest
	(*DeleteScheduleResponse)(nil),  // 9: apps.v0.DeleteScheduleResponse
	(*ScheduleNameRequest)(nil),     // 10: apps.v0.ScheduleNameRequest
	(*TriggerResponse)(nil),         // 11: apps.v0.TriggerResponse
	(*ScheduleHistoryRequest)(nil),  // 12: apps.v0.ScheduleHistoryRequest
	(*ScheduleHistoryResponse)(nil), // 13: apps.v0.ScheduleHistoryResponse
	(*ScheduleHistoryEntry)(nil),    // 14: apps.v0.ScheduleHistoryEntry
	nil,                             // 15: apps.v0.Schedule.MetadataEntry
	nil,                             // 16: apps.v0.ScheduleTrigger.MetadataEntry
	nil,                             // 17: apps.v0.CreateScheduleRequest.MetadataEntry
	nil,                             // 18: apps.v0.UpdateScheduleRequest.MetadataEntry
	(*HealthCheckRequest)(nil),      // 19: apps.v0.HealthCheckRequest
	(*Empty)(nil),                   // 20: apps.v0.Empty
	(*SettingsMap)(nil),             // 21: apps.v0.SettingsMap
	(*HealthCheckResponse)(nil),     // 22: apps.v0.HealthCheckResponse
}
var file_proto_apps_v0_schedule_proto_depIdxs = []int32{
	15, // 0: apps.v0.Schedule.metadata:type_name -> apps.v0.Schedule.MetadataEntry
	16, // 1: apps.v0.ScheduleTrigger.metadata:type_name -> apps.v0.ScheduleTrigger.MetadataEntry
	17, // 2: apps.v0.CreateScheduleRequest.metadata:type_name -> apps.v0.CreateScheduleRequest.MetadataEntry
	0,  // 3: apps.v0.ListSchedulesResponse.schedules:type_name -> apps.v0.Schedule
	18, // 4: apps.v0.UpdateScheduleRequest.metadata:type_name -> apps.v0.UpdateScheduleRequest.MetadataEntry
	0,  // 5: apps.v0.ScheduleResponse.schedule:type_name -> apps.v0.Schedule
	14, // 6: apps.v0.ScheduleHistoryResponse.entries:type_name -> apps.v0.ScheduleHistoryEntry
	19, // 7: apps.v0.ScheduleService.HealthCheck:input_type -> apps.v0.HealthCheckRequest
	2,  // 8: apps.v0.ScheduleService.Create:input_type -> apps.v0.CreateScheduleRequest
	3,  // 9: apps.v0.ScheduleService.Get:input_type -> apps.v0.GetScheduleRequest
	4,  // 10: apps.v0.ScheduleService.List:input_type -> apps.v0.ListSchedulesRequest
	6,  // 11: apps.v0.ScheduleService.Update:input_type -> apps.v0.UpdateScheduleRequest
	8,  // 12: apps.v0.ScheduleService.Delete:input_type -> apps.v0.DeleteScheduleRequest
	10, // 13: apps.v0.ScheduleService.Enable:input_type -> apps.v0.ScheduleNameRequest
	10, // 14: apps.v0.ScheduleService.Disable:input_type -> apps.v0.ScheduleNameRequest
	10, // 15: apps.v0.ScheduleService.Trigger:input_type -> apps.v0.ScheduleNameRequest
	12, // 16: apps.v0.ScheduleService.History:input_type -> apps.v0.ScheduleHistoryRequest
	20, // 17: apps.v0.ScheduleService.Triggers:input_type -> apps.v0.Empty
	21, // 18: apps.v0.ScheduleService.Configure:input_type -> apps.v0.SettingsMap
	22, // 19: apps.v0.ScheduleService.HealthCheck:output_type -> apps.v0.HealthCheckResponse
	7,  // 20: apps.v0.ScheduleService.Create:output_type -> apps.v0.ScheduleResponse
	7,  // 21: apps.v0.ScheduleService.Get:output_type -> apps.v0.ScheduleResponse
	5,  // 22: apps.v0.ScheduleService.List:output_type -> apps.v0.ListSchedulesResponse
	7,  // 23: apps.v0.ScheduleService.Update:output_type -> apps.v0.ScheduleResponse
	9,  // 24: apps.v0.ScheduleService.Delete:output_type -> apps.v0.DeleteScheduleResponse
	7,  // 25: apps.v0.ScheduleService.Enable:output_type -> apps.v0.ScheduleResponse
	7,  // 26: apps.v0.ScheduleService.Disable:output_type -> apps.v0.ScheduleResponse
	11, // 27: apps.v0.ScheduleService.Trigger:output_type -> apps.v0.TriggerResponse
	13, // 28: apps.v0.ScheduleService.History:output_type -> apps.v0.ScheduleHistoryResponse
	1,  // 29: apps.v0.ScheduleService.Triggers:output_type -> apps.v0.ScheduleTrigger
	20, // 30: apps.v0.ScheduleService.Configure:output_type -> apps.v0.Empty
	19, // [19:31] is the sub-list for method output_type
	7,  // [7:19] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_apps_v0_schedule_proto_init() }
func file_proto_apps_v0_schedule_proto_init() {
	if File_proto_apps_v0_schedule_proto != nil {
		return
	}
	file_proto_apps_v0_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_apps_v0_schedule_proto_rawDesc), len(file_proto_apps_v0_schedule_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_apps_v0_schedule_proto_goTypes,
		DependencyIndexes: file_proto_apps_v0_schedule_proto_depIdxs,
		MessageInfos:      file_proto_apps_v0_schedule_proto_msgTypes,
	}.Build()
	File_proto_apps_v0_schedule_proto = out.File
	file_proto_apps_v0_schedule_proto_goTypes = nil
	file_proto_apps_v0_schedule_proto_depIdxs = nil
}
