// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.0
// source: proto/apps/v0/schedule.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ScheduleService_HealthCheck_FullMethodName = "/apps.v0.ScheduleService/HealthCheck"
	ScheduleService_Create_FullMethodName      = "/apps.v0.ScheduleService/Create"
	ScheduleService_Get_FullMethodName         = "/apps.v0.ScheduleService/Get"
	ScheduleService_List_FullMethodName        = "/apps.v0.ScheduleService/List"
	ScheduleService_Update_FullMethodName      = "/apps.v0.ScheduleService/Update"
	ScheduleService_Delete_FullMethodName      = "/apps.v0.ScheduleService/Delete"
	ScheduleService_Enable_FullMethodName      = "/apps.v0.ScheduleService/Enable"
	ScheduleService_Disable_FullMethodName     = "/apps.v0.ScheduleService/Disable"
	ScheduleService_Trigger_FullMethodName     = "/apps.v0.ScheduleService/Trigger"
	ScheduleService_History_FullMethodName     = "/apps.v0.ScheduleService/History"
	ScheduleService_Triggers_FullMethodName    = "/apps.v0.ScheduleService/Triggers"
	ScheduleService_Configure_FullMethodName   = "/apps.v0.ScheduleService/Configure"
)

// ScheduleServiceClient is the client API for ScheduleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ScheduleService is the interface for apps that provide scheduling capabilities.
// Apps that provide this service replace the built-in cron scheduler.
// The app owns its own schedule state and notifies Nebo via a trigger stream
// when a schedule fires.
type ScheduleServiceClient interface {
	// HealthCheck verifies the schedule app is running.
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// Create creates a new schedule.
	Create(ctx context.Context, in *CreateScheduleRequest, opts ...grpc.CallOption) (*ScheduleResponse, error)
	// Get returns a single schedule by name.
	Get(ctx context.Context, in *GetScheduleRequest, opts ...grpc.CallOption) (*ScheduleResponse, error)
	// List returns all schedules with optional pagination.
	List(ctx context.Context, in *ListSchedulesRequest, opts ...grpc.CallOption) (*ListSchedulesResponse, error)
	// Update modifies an existing schedule.
	Update(ctx context.Context, in *UpdateScheduleRequest, opts ...grpc.CallOption) (*ScheduleResponse, error)
	// Delete removes a schedule.
	Delete(ctx context.Context, in *DeleteScheduleRequest, opts ...grpc.CallOption) (*DeleteScheduleResponse, error)
	// Enable activates a disabled schedule.
	Enable(ctx context.Context, in *ScheduleNameRequest, opts ...grpc.CallOption) (*ScheduleResponse, error)
	// Disable deactivates a schedule without deleting it.
	Disable(ctx context.Context, in *ScheduleNameRequest, opts ...grpc.CallOption) (*ScheduleResponse, error)
	// Trigger manually fires a schedule immediately.
	Trigger(ctx context.Context, in *ScheduleNameRequest, opts ...grpc.CallOption) (*TriggerResponse, error)
	// History returns execution history for a schedule.
	History(ctx context.Context, in *ScheduleHistoryRequest, opts ...grpc.CallOption) (*ScheduleHistoryResponse, error)
	// Triggers is a server-streaming RPC. The app notifies Nebo each time a schedule fires.
	// Nebo reads from this stream and routes the triggered task to LaneEvents.
	Triggers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScheduleTrigger], error)
	// Configure updates the app's settings.
	Configure(ctx context.Context, in *SettingsMap, opts ...grpc.CallOption) (*Empty, error)
}

type scheduleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewScheduleServiceClient(cc grpc.ClientConnInterface) ScheduleServiceClient {
	return &scheduleServiceClient{cc}
}

func (c *scheduleServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, ScheduleService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleServiceClient) Create(ctx context.Context, in *CreateScheduleRequest, opts ...grpc.CallOption) (*ScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScheduleResponse)
	err := c.cc.Invoke(ctx, ScheduleService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleServiceClient) Get(ctx context.Context, in *GetScheduleRequest, opts ...grpc.CallOption) (*ScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScheduleResponse)
	err := c.cc.Invoke(ctx, ScheduleService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleServiceClient) List(ctx context.Context, in *ListSchedulesRequest, opts ...grpc.CallOption) (*ListSchedulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSchedulesResponse)
	err := c.cc.Invoke(ctx, ScheduleService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleServiceClient) Update(ctx context.Context, in *UpdateScheduleRequest, opts ...grpc.CallOption) (*ScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScheduleResponse)
	err := c.cc.Invoke(ctx, ScheduleService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleServiceClient) Delete(ctx context.Context, in *DeleteScheduleRequest, opts ...grpc.CallOption) (*DeleteScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteScheduleResponse)
	err := c.cc.Invoke(ctx, ScheduleService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleServiceClient) Enable(ctx context.Context, in *ScheduleNameRequest, opts ...grpc.CallOption) (*ScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScheduleResponse)
	err := c.cc.Invoke(ctx, ScheduleService_Enable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleServiceClient) Disable(ctx context.Context, in *ScheduleNameRequest, opts ...grpc.CallOption) (*ScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScheduleResponse)
	err := c.cc.Invoke(ctx, ScheduleService_Disable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleServiceClient) Trigger(ctx context.Context, in *ScheduleNameRequest, opts ...grpc.CallOption) (*TriggerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerResponse)
	err := c.cc.Invoke(ctx, ScheduleService_Trigger_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleServiceClient) History(ctx context.Context, in *ScheduleHistoryRequest, opts ...grpc.CallOption) (*ScheduleHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScheduleHistoryResponse)
	err := c.cc.Invoke(ctx, ScheduleService_History_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleServiceClient) Triggers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScheduleTrigger], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ScheduleService_ServiceDesc.Streams[0], ScheduleService_Triggers_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, ScheduleTrigger]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ScheduleService_TriggersClient = grpc.ServerStreamingClient[ScheduleTrigger]

func (c *scheduleServiceClient) Configure(ctx context.Context, in *SettingsMap, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ScheduleService_Configure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScheduleServiceServer is the server API for ScheduleService service.
// All implementations must embed UnimplementedScheduleServiceServer
// for forward compatibility.
//
// ScheduleService is the interface for apps that provide scheduling capabilities.
// Apps that provide this service replace the built-in cron scheduler.
// The app owns its own schedule state and notifies Nebo via a trigger stream
// when a schedule fires.
type ScheduleServiceServer interface {
	// HealthCheck verifies the schedule app is running.
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// Create creates a new schedule.
	Create(context.Context, *CreateScheduleRequest) (*ScheduleResponse, error)
	// Get returns a single schedule by name.
	Get(context.Context, *GetScheduleRequest) (*ScheduleResponse, error)
	// List returns all schedules with optional pagination.
	List(context.Context, *ListSchedulesRequest) (*ListSchedulesResponse, error)
	// Update modifies an existing schedule.
	Update(context.Context, *UpdateScheduleRequest) (*ScheduleResponse, error)
	// Delete removes a schedule.
	Delete(context.Context, *DeleteScheduleRequest) (*DeleteScheduleResponse, error)
	// Enable activates a disabled schedule.
	Enable(context.Context, *ScheduleNameRequest) (*ScheduleResponse, error)
	// Disable deactivates a schedule without deleting it.
	Disable(context.Context, *ScheduleNameRequest) (*ScheduleResponse, error)
	// Trigger manually fires a schedule immediately.
	Trigger(context.Context, *ScheduleNameRequest) (*TriggerResponse, error)
	// History returns execution history for a schedule.
	History(context.Context, *ScheduleHistoryRequest) (*ScheduleHistoryResponse, error)
	// Triggers is a server-streaming RPC. The app notifies Nebo each time a schedule fires.
	// Nebo reads from this stream and routes the triggered task to LaneEvents.
	Triggers(*Empty, grpc.ServerStreamingServer[ScheduleTrigger]) error
	// Configure updates the app's settings.
	Configure(context.Context, *SettingsMap) (*Empty, error)
	mustEmbedUnimplementedScheduleServiceServer()
}

// UnimplementedScheduleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScheduleServiceServer struct{}

func (UnimplementedScheduleServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedScheduleServiceServer) Create(context.Context, *CreateScheduleRequest) (*ScheduleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedScheduleServiceServer) Get(context.Context, *GetScheduleRequest) (*ScheduleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedScheduleServiceServer) List(context.Context, *ListSchedulesRequest) (*ListSchedulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedScheduleServiceServer) Update(context.Context, *UpdateScheduleRequest) (*ScheduleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedScheduleServiceServer) Delete(context.Context, *DeleteScheduleRequest) (*DeleteScheduleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedScheduleServiceServer) Enable(context.Context, *ScheduleNameRequest) (*ScheduleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Enable not implemented")
}
func (UnimplementedScheduleServiceServer) Disable(context.Context, *ScheduleNameRequest) (*ScheduleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Disable not implemented")
}
func (UnimplementedScheduleServiceServer) Trigger(context.Context, *ScheduleNameRequest) (*TriggerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Trigger not implemented")
}
func (UnimplementedScheduleServiceServer) History(context.Context, *ScheduleHistoryRequest) (*ScheduleHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method History not implemented")
}
func (UnimplementedScheduleServiceServer) Triggers(*Empty, grpc.ServerStreamingServer[ScheduleTrigger]) error {
	return status.Error(codes.Unimplemented, "method Triggers not implemented")
}
func (UnimplementedScheduleServiceServer) Configure(context.Context, *SettingsMap) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Configure not implemented")
}
func (UnimplementedScheduleServiceServer) mustEmbedUnimplementedScheduleServiceServer() {}
func (UnimplementedScheduleServiceServer) testEmbeddedByValue()                         {}

// UnsafeScheduleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScheduleServiceServer will
// result in compilation errors.
type UnsafeScheduleServiceServer interface {
	mustEmbedUnimplementedScheduleServiceServer()
}

func RegisterScheduleServiceServer(s grpc.ServiceRegistrar, srv ScheduleServiceServer) {
	// If the following call panics, it indicates UnimplementedScheduleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScheduleService_ServiceDesc, srv)
}

func _ScheduleService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScheduleService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduleService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScheduleService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServiceServer).Create(ctx, req.(*CreateScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduleService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScheduleService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServiceServer).Get(ctx, req.(*GetScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduleService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSchedulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScheduleService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServiceServer).List(ctx, req.(*ListSchedulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduleService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScheduleService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServiceServer).Update(ctx, req.(*UpdateScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduleService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScheduleService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServiceServer).Delete(ctx, req.(*DeleteScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduleService_Enable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServiceServer).Enable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScheduleService_Enable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServiceServer).Enable(ctx, req.(*ScheduleNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduleService_Disable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServiceServer).Disable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScheduleService_Disable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServiceServer).Disable(ctx, req.(*ScheduleNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduleService_Trigger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServiceServer).Trigger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScheduleService_Trigger_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServiceServer).Trigger(ctx, req.(*ScheduleNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduleService_History_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServiceServer).History(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScheduleService_History_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServiceServer).History(ctx, req.(*ScheduleHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduleService_Triggers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ScheduleServiceServer).Triggers(m, &grpc.GenericServerStream[Empty, ScheduleTrigger]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ScheduleService_TriggersServer = grpc.ServerStreamingServer[ScheduleTrigger]

func _ScheduleService_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettingsMap)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServiceServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScheduleService_Configure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServiceServer).Configure(ctx, req.(*SettingsMap))
	}
	return interceptor(ctx, in, info, handler)
}

// ScheduleService_ServiceDesc is the grpc.ServiceDesc for ScheduleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScheduleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "apps.v0.ScheduleService",
	HandlerType: (*ScheduleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _ScheduleService_HealthCheck_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _ScheduleService_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ScheduleService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _ScheduleService_List_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ScheduleService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ScheduleService_Delete_Handler,
		},
		{
			MethodName: "Enable",
			Handler:    _ScheduleService_Enable_Handler,
		},
		{
			MethodName: "Disable",
			Handler:    _ScheduleService_Disable_Handler,
		},
		{
			MethodName: "Trigger",
			Handler:    _ScheduleService_Trigger_Handler,
		},
		{
			MethodName: "History",
			Handler:    _ScheduleService_History_Handler,
		},
		{
			MethodName: "Configure",
			Handler:    _ScheduleService_Configure_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Triggers",
			Handler:       _ScheduleService_Triggers_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/apps/v0/schedule.proto",
}
