// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: proto/apps/v0/tool.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ToolService_HealthCheck_FullMethodName      = "/apps.v0.ToolService/HealthCheck"
	ToolService_Name_FullMethodName             = "/apps.v0.ToolService/Name"
	ToolService_Description_FullMethodName      = "/apps.v0.ToolService/Description"
	ToolService_Schema_FullMethodName           = "/apps.v0.ToolService/Schema"
	ToolService_Execute_FullMethodName          = "/apps.v0.ToolService/Execute"
	ToolService_RequiresApproval_FullMethodName = "/apps.v0.ToolService/RequiresApproval"
	ToolService_Configure_FullMethodName        = "/apps.v0.ToolService/Configure"
)

// ToolServiceClient is the client API for ToolService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ToolService is the interface for tool apps that extend agent capabilities.
type ToolServiceClient interface {
	// HealthCheck verifies the tool app is running.
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// Name returns the tool's unique identifier.
	Name(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NameResponse, error)
	// Description returns a human-readable description.
	Description(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DescriptionResponse, error)
	// Schema returns the JSON Schema for the tool's input.
	Schema(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SchemaResponse, error)
	// Execute runs the tool with the given input.
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
	// RequiresApproval indicates if this tool needs user confirmation.
	RequiresApproval(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ApprovalResponse, error)
	// Configure updates the app's settings.
	Configure(ctx context.Context, in *SettingsMap, opts ...grpc.CallOption) (*Empty, error)
}

type toolServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewToolServiceClient(cc grpc.ClientConnInterface) ToolServiceClient {
	return &toolServiceClient{cc}
}

func (c *toolServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, ToolService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolServiceClient) Name(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NameResponse)
	err := c.cc.Invoke(ctx, ToolService_Name_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolServiceClient) Description(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DescriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescriptionResponse)
	err := c.cc.Invoke(ctx, ToolService_Description_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolServiceClient) Schema(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SchemaResponse)
	err := c.cc.Invoke(ctx, ToolService_Schema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolServiceClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, ToolService_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolServiceClient) RequiresApproval(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ApprovalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApprovalResponse)
	err := c.cc.Invoke(ctx, ToolService_RequiresApproval_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolServiceClient) Configure(ctx context.Context, in *SettingsMap, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ToolService_Configure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ToolServiceServer is the server API for ToolService service.
// All implementations must embed UnimplementedToolServiceServer
// for forward compatibility.
//
// ToolService is the interface for tool apps that extend agent capabilities.
type ToolServiceServer interface {
	// HealthCheck verifies the tool app is running.
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// Name returns the tool's unique identifier.
	Name(context.Context, *Empty) (*NameResponse, error)
	// Description returns a human-readable description.
	Description(context.Context, *Empty) (*DescriptionResponse, error)
	// Schema returns the JSON Schema for the tool's input.
	Schema(context.Context, *Empty) (*SchemaResponse, error)
	// Execute runs the tool with the given input.
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
	// RequiresApproval indicates if this tool needs user confirmation.
	RequiresApproval(context.Context, *Empty) (*ApprovalResponse, error)
	// Configure updates the app's settings.
	Configure(context.Context, *SettingsMap) (*Empty, error)
	mustEmbedUnimplementedToolServiceServer()
}

// UnimplementedToolServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedToolServiceServer struct{}

func (UnimplementedToolServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedToolServiceServer) Name(context.Context, *Empty) (*NameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Name not implemented")
}
func (UnimplementedToolServiceServer) Description(context.Context, *Empty) (*DescriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Description not implemented")
}
func (UnimplementedToolServiceServer) Schema(context.Context, *Empty) (*SchemaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Schema not implemented")
}
func (UnimplementedToolServiceServer) Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedToolServiceServer) RequiresApproval(context.Context, *Empty) (*ApprovalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequiresApproval not implemented")
}
func (UnimplementedToolServiceServer) Configure(context.Context, *SettingsMap) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Configure not implemented")
}
func (UnimplementedToolServiceServer) mustEmbedUnimplementedToolServiceServer() {}
func (UnimplementedToolServiceServer) testEmbeddedByValue()                     {}

// UnsafeToolServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ToolServiceServer will
// result in compilation errors.
type UnsafeToolServiceServer interface {
	mustEmbedUnimplementedToolServiceServer()
}

func RegisterToolServiceServer(s grpc.ServiceRegistrar, srv ToolServiceServer) {
	// If the following call panics, it indicates UnimplementedToolServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ToolService_ServiceDesc, srv)
}

func _ToolService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolService_Name_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).Name(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolService_Name_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).Name(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolService_Description_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).Description(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolService_Description_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).Description(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolService_Schema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).Schema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolService_Schema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).Schema(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolService_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolService_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolService_RequiresApproval_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).RequiresApproval(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolService_RequiresApproval_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).RequiresApproval(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolService_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettingsMap)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolService_Configure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).Configure(ctx, req.(*SettingsMap))
	}
	return interceptor(ctx, in, info, handler)
}

// ToolService_ServiceDesc is the grpc.ServiceDesc for ToolService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ToolService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "apps.v0.ToolService",
	HandlerType: (*ToolServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _ToolService_HealthCheck_Handler,
		},
		{
			MethodName: "Name",
			Handler:    _ToolService_Name_Handler,
		},
		{
			MethodName: "Description",
			Handler:    _ToolService_Description_Handler,
		},
		{
			MethodName: "Schema",
			Handler:    _ToolService_Schema_Handler,
		},
		{
			MethodName: "Execute",
			Handler:    _ToolService_Execute_Handler,
		},
		{
			MethodName: "RequiresApproval",
			Handler:    _ToolService_RequiresApproval_Handler,
		},
		{
			MethodName: "Configure",
			Handler:    _ToolService_Configure_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/apps/v0/tool.proto",
}
