// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/apps/v0/tool.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NameResponse) Reset() {
	*x = NameResponse{}
	mi := &file_proto_apps_v0_tool_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameResponse) ProtoMessage() {}

func (x *NameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_tool_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameResponse.ProtoReflect.Descriptor instead.
func (*NameResponse) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_tool_proto_rawDescGZIP(), []int{0}
}

func (x *NameResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DescriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescriptionResponse) Reset() {
	*x = DescriptionResponse{}
	mi := &file_proto_apps_v0_tool_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescriptionResponse) ProtoMessage() {}

func (x *DescriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_tool_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescriptionResponse.ProtoReflect.Descriptor instead.
func (*DescriptionResponse) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_tool_proto_rawDescGZIP(), []int{1}
}

func (x *DescriptionResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type SchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        []byte                 `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"` // JSON Schema
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaResponse) Reset() {
	*x = SchemaResponse{}
	mi := &file_proto_apps_v0_tool_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaResponse) ProtoMessage() {}

func (x *SchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_tool_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaResponse.ProtoReflect.Descriptor instead.
func (*SchemaResponse) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_tool_proto_rawDescGZIP(), []int{2}
}

func (x *SchemaResponse) GetSchema() []byte {
	if x != nil {
		return x.Schema
	}
	return nil
}

type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         []byte                 `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"` // JSON-encoded tool input
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_proto_apps_v0_tool_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_tool_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_tool_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteRequest) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	IsError       bool                   `protobuf:"varint,2,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_proto_apps_v0_tool_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_tool_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_tool_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ExecuteResponse) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

type ApprovalResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RequiresApproval bool                   `protobuf:"varint,1,opt,name=requires_approval,json=requiresApproval,proto3" json:"requires_approval,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ApprovalResponse) Reset() {
	*x = ApprovalResponse{}
	mi := &file_proto_apps_v0_tool_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalResponse) ProtoMessage() {}

func (x *ApprovalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_tool_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalResponse.ProtoReflect.Descriptor instead.
func (*ApprovalResponse) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_tool_proto_rawDescGZIP(), []int{5}
}

func (x *ApprovalResponse) GetRequiresApproval() bool {
	if x != nil {
		return x.RequiresApproval
	}
	return false
}

var File_proto_apps_v0_tool_proto protoreflect.FileDescriptor

const file_proto_apps_v0_tool_proto_rawDesc = "" +
	"\n" +
	"\x18proto/apps/v0/tool.proto\x12\aapps.v0\x1a\x1aproto/apps/v0/common.proto\"\"\n" +
	"\fNameResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"7\n" +
	"\x13DescriptionResponse\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\"(\n" +
	"\x0eSchemaResponse\x12\x16\n" +
	"\x06schema\x18\x01 \x01(\fR\x06schema\"&\n" +
	"\x0eExecuteRequest\x12\x14\n" +
	"\x05input\x18\x01 \x01(\fR\x05input\"F\n" +
	"\x0fExecuteResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x19\n" +
	"\bis_error\x18\x02 \x01(\bR\aisError\"?\n" +
	"\x10ApprovalResponse\x12+\n" +
	"\x11requires_approval\x18\x01 \x01(\bR\x10requiresApproval2\xa6\x03\n" +
	"\vToolService\x12H\n" +
	"\vHealthCheck\x12\x1b.apps.v0.HealthCheckRequest\x1a\x1c.apps.v0.HealthCheckResponse\x12-\n" +
	"\x04Name\x12\x0e.apps.v0.Empty\x1a\x15.apps.v0.NameResponse\x12;\n" +
	"\vDescription\x12\x0e.apps.v0.Empty\x1a\x1c.apps.v0.DescriptionResponse\x121\n" +
	"\x06Schema\x12\x0e.apps.v0.Empty\x1a\x17.apps.v0.SchemaResponse\x12<\n" +
	"\aExecute\x12\x17.apps.v0.ExecuteRequest\x1a\x18.apps.v0.ExecuteResponse\x12=\n" +
	"\x10RequiresApproval\x12\x0e.apps.v0.Empty\x1a\x19.apps.v0.ApprovalResponse\x121\n" +
	"\tConfigure\x12\x14.apps.v0.SettingsMap\x1a\x0e.apps.v0.EmptyB$Z\"github.com/nebolabs/nebo-sdk-go/pbb\x06proto3"

var (
	file_proto_apps_v0_tool_proto_rawDescOnce sync.Once
	file_proto_apps_v0_tool_proto_rawDescData []byte
)

func file_proto_apps_v0_tool_proto_rawDescGZIP() []byte {
	file_proto_apps_v0_tool_proto_rawDescOnce.Do(func() {
		file_proto_apps_v0_tool_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_apps_v0_tool_proto_rawDesc), len(file_proto_apps_v0_tool_proto_rawDesc)))
	})
	return file_proto_apps_v0_tool_proto_rawDescData
}

var file_proto_apps_v0_tool_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_apps_v0_tool_proto_goTypes = []any{
	(*NameResponse)(nil),        // 0: apps.v0.NameResponse
	(*DescriptionResponse)(nil), // 1: apps.v0.DescriptionResponse
	(*SchemaResponse)(nil),      // 2: apps.v0.SchemaResponse
	(*ExecuteRequest)(nil),      // 3: apps.v0.ExecuteRequest
	(*ExecuteResponse)(nil),     // 4: apps.v0.ExecuteResponse
	(*ApprovalResponse)(nil),    // 5: apps.v0.ApprovalResponse
	(*HealthCheckRequest)(nil),  // 6: apps.v0.HealthCheckRequest
	(*Empty)(nil),               // 7: apps.v0.Empty
	(*SettingsMap)(nil),         // 8: apps.v0.SettingsMap
	(*HealthCheckResponse)(nil), // 9: apps.v0.HealthCheckResponse
}
var file_proto_apps_v0_tool_proto_depIdxs = []int32{
	6, // 0: apps.v0.ToolService.HealthCheck:input_type -> apps.v0.HealthCheckRequest
	7, // 1: apps.v0.ToolService.Name:input_type -> apps.v0.Empty
	7, // 2: apps.v0.ToolService.Description:input_type -> apps.v0.Empty
	7, // 3: apps.v0.ToolService.Schema:input_type -> apps.v0.Empty
	3, // 4: apps.v0.ToolService.Execute:input_type -> apps.v0.ExecuteRequest
	7, // 5: apps.v0.ToolService.RequiresApproval:input_type -> apps.v0.Empty
	8, // 6: apps.v0.ToolService.Configure:input_type -> apps.v0.SettingsMap
	9, // 7: apps.v0.ToolService.HealthCheck:output_type -> apps.v0.HealthCheckResponse
	0, // 8: apps.v0.ToolService.Name:output_type -> apps.v0.NameResponse
	1, // 9: apps.v0.ToolService.Description:output_type -> apps.v0.DescriptionResponse
	2, // 10: apps.v0.ToolService.Schema:output_type -> apps.v0.SchemaResponse
	4, // 11: apps.v0.ToolService.Execute:output_type -> apps.v0.ExecuteResponse
	5, // 12: apps.v0.ToolService.RequiresApproval:output_type -> apps.v0.ApprovalResponse
	7, // 13: apps.v0.ToolService.Configure:output_type -> apps.v0.Empty
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_apps_v0_tool_proto_init() }
func file_proto_apps_v0_tool_proto_init() {
	if File_proto_apps_v0_tool_proto != nil {
		return
	}
	file_proto_apps_v0_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_apps_v0_tool_proto_rawDesc), len(file_proto_apps_v0_tool_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_apps_v0_tool_proto_goTypes,
		DependencyIndexes: file_proto_apps_v0_tool_proto_depIdxs,
		MessageInfos:      file_proto_apps_v0_tool_proto_msgTypes,
	}.Build()
	File_proto_apps_v0_tool_proto = out.File
	file_proto_apps_v0_tool_proto_goTypes = nil
	file_proto_apps_v0_tool_proto_depIdxs = nil
}
