// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.4
// source: proto/apps/v0/ui.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HttpRequest represents an HTTP request proxied from the browser to the app.
type HttpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`                                                                             // GET, POST, PUT, DELETE, etc.
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`                                                                                 // Path relative to /apps/{id}/api/
	Query         string                 `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`                                                                               // Raw query string (e.g. "page=1&size=10")
	Headers       map[string]string      `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Request headers
	Body          []byte                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`                                                                                 // Request body (empty for GET/HEAD)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpRequest) Reset() {
	*x = HttpRequest{}
	mi := &file_proto_apps_v0_ui_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpRequest) ProtoMessage() {}

func (x *HttpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_ui_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpRequest.ProtoReflect.Descriptor instead.
func (*HttpRequest) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_ui_proto_rawDescGZIP(), []int{0}
}

func (x *HttpRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HttpRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HttpRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *HttpRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HttpRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// HttpResponse represents an HTTP response from the app back to the browser.
type HttpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`                                                  // HTTP status code (200, 404, 500, etc.)
	Headers       map[string]string      `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Response headers
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`                                                                                 // Response body
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpResponse) Reset() {
	*x = HttpResponse{}
	mi := &file_proto_apps_v0_ui_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpResponse) ProtoMessage() {}

func (x *HttpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_ui_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpResponse.ProtoReflect.Descriptor instead.
func (*HttpResponse) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_ui_proto_rawDescGZIP(), []int{1}
}

func (x *HttpResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *HttpResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HttpResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

var File_proto_apps_v0_ui_proto protoreflect.FileDescriptor

const file_proto_apps_v0_ui_proto_rawDesc = "" +
	"\n" +
	"\x16proto/apps/v0/ui.proto\x12\aapps.v0\x1a\x1aproto/apps/v0/common.proto\"\xdc\x01\n" +
	"\vHttpRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x14\n" +
	"\x05query\x18\x03 \x01(\tR\x05query\x12;\n" +
	"\aheaders\x18\x04 \x03(\v2!.apps.v0.HttpRequest.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x05 \x01(\fR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbd\x01\n" +
	"\fHttpResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12<\n" +
	"\aheaders\x18\x02 \x03(\v2\".apps.v0.HttpResponse.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xc6\x01\n" +
	"\tUIService\x12H\n" +
	"\vHealthCheck\x12\x1b.apps.v0.HealthCheckRequest\x1a\x1c.apps.v0.HealthCheckResponse\x121\n" +
	"\tConfigure\x12\x14.apps.v0.SettingsMap\x1a\x0e.apps.v0.Empty\x12<\n" +
	"\rHandleRequest\x12\x14.apps.v0.HttpRequest\x1a\x15.apps.v0.HttpResponseB$Z\"github.com/neboloop/nebo-sdk-go/pbb\x06proto3"

var (
	file_proto_apps_v0_ui_proto_rawDescOnce sync.Once
	file_proto_apps_v0_ui_proto_rawDescData []byte
)

func file_proto_apps_v0_ui_proto_rawDescGZIP() []byte {
	file_proto_apps_v0_ui_proto_rawDescOnce.Do(func() {
		file_proto_apps_v0_ui_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_apps_v0_ui_proto_rawDesc), len(file_proto_apps_v0_ui_proto_rawDesc)))
	})
	return file_proto_apps_v0_ui_proto_rawDescData
}

var file_proto_apps_v0_ui_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_apps_v0_ui_proto_goTypes = []any{
	(*HttpRequest)(nil),         // 0: apps.v0.HttpRequest
	(*HttpResponse)(nil),        // 1: apps.v0.HttpResponse
	nil,                         // 2: apps.v0.HttpRequest.HeadersEntry
	nil,                         // 3: apps.v0.HttpResponse.HeadersEntry
	(*HealthCheckRequest)(nil),  // 4: apps.v0.HealthCheckRequest
	(*SettingsMap)(nil),         // 5: apps.v0.SettingsMap
	(*HealthCheckResponse)(nil), // 6: apps.v0.HealthCheckResponse
	(*Empty)(nil),               // 7: apps.v0.Empty
}
var file_proto_apps_v0_ui_proto_depIdxs = []int32{
	2, // 0: apps.v0.HttpRequest.headers:type_name -> apps.v0.HttpRequest.HeadersEntry
	3, // 1: apps.v0.HttpResponse.headers:type_name -> apps.v0.HttpResponse.HeadersEntry
	4, // 2: apps.v0.UIService.HealthCheck:input_type -> apps.v0.HealthCheckRequest
	5, // 3: apps.v0.UIService.Configure:input_type -> apps.v0.SettingsMap
	0, // 4: apps.v0.UIService.HandleRequest:input_type -> apps.v0.HttpRequest
	6, // 5: apps.v0.UIService.HealthCheck:output_type -> apps.v0.HealthCheckResponse
	7, // 6: apps.v0.UIService.Configure:output_type -> apps.v0.Empty
	1, // 7: apps.v0.UIService.HandleRequest:output_type -> apps.v0.HttpResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_apps_v0_ui_proto_init() }
func file_proto_apps_v0_ui_proto_init() {
	if File_proto_apps_v0_ui_proto != nil {
		return
	}
	file_proto_apps_v0_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_apps_v0_ui_proto_rawDesc), len(file_proto_apps_v0_ui_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_apps_v0_ui_proto_goTypes,
		DependencyIndexes: file_proto_apps_v0_ui_proto_depIdxs,
		MessageInfos:      file_proto_apps_v0_ui_proto_msgTypes,
	}.Build()
	File_proto_apps_v0_ui_proto = out.File
	file_proto_apps_v0_ui_proto_goTypes = nil
	file_proto_apps_v0_ui_proto_depIdxs = nil
}
