// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/apps/v0/ui.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetViewRequest asks the app for its current UI view.
type GetViewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       string                 `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"` // Optional: context hint (e.g., "settings", "main")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetViewRequest) Reset() {
	*x = GetViewRequest{}
	mi := &file_proto_apps_v0_ui_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetViewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetViewRequest) ProtoMessage() {}

func (x *GetViewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_ui_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetViewRequest.ProtoReflect.Descriptor instead.
func (*GetViewRequest) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_ui_proto_rawDescGZIP(), []int{0}
}

func (x *GetViewRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

// UIView is a complete renderable view pushed by an app.
type UIView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ViewId        string                 `protobuf:"bytes,1,opt,name=view_id,json=viewId,proto3" json:"view_id,omitempty"` // Unique identifier for this view (for deduplication)
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`                 // Panel title
	Blocks        []*UIBlock             `protobuf:"bytes,3,rep,name=blocks,proto3" json:"blocks,omitempty"`               // Ordered list of UI blocks to render
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UIView) Reset() {
	*x = UIView{}
	mi := &file_proto_apps_v0_ui_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIView) ProtoMessage() {}

func (x *UIView) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_ui_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIView.ProtoReflect.Descriptor instead.
func (*UIView) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_ui_proto_rawDescGZIP(), []int{1}
}

func (x *UIView) GetViewId() string {
	if x != nil {
		return x.ViewId
	}
	return ""
}

func (x *UIView) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UIView) GetBlocks() []*UIBlock {
	if x != nil {
		return x.Blocks
	}
	return nil
}

// UIBlock is a single renderable element in a view.
type UIBlock struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	BlockId string                 `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"` // Unique ID for this block (used in events)
	Type    string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`                      // Block type: text, heading, input, button, select, toggle, divider, image
	// Common fields (used by relevant block types)
	Text        string `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`               // text, heading, button label
	Value       string `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`             // input value, select value, toggle state ("true"/"false")
	Placeholder string `protobuf:"bytes,5,opt,name=placeholder,proto3" json:"placeholder,omitempty"` // input placeholder
	Hint        string `protobuf:"bytes,6,opt,name=hint,proto3" json:"hint,omitempty"`               // helper text below inputs
	Variant     string `protobuf:"bytes,7,opt,name=variant,proto3" json:"variant,omitempty"`         // button: primary/secondary/ghost/error; heading: h1/h2/h3
	Src         string `protobuf:"bytes,8,opt,name=src,proto3" json:"src,omitempty"`                 // image source URL
	Alt         string `protobuf:"bytes,9,opt,name=alt,proto3" json:"alt,omitempty"`                 // image alt text
	Disabled    bool   `protobuf:"varint,10,opt,name=disabled,proto3" json:"disabled,omitempty"`     // button, input, select, toggle
	// Select-specific
	Options []*SelectOption `protobuf:"bytes,11,rep,name=options,proto3" json:"options,omitempty"`
	// Layout
	Style         string `protobuf:"bytes,12,opt,name=style,proto3" json:"style,omitempty"` // compact, full-width (optional layout hints, not CSS)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UIBlock) Reset() {
	*x = UIBlock{}
	mi := &file_proto_apps_v0_ui_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIBlock) ProtoMessage() {}

func (x *UIBlock) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_ui_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIBlock.ProtoReflect.Descriptor instead.
func (*UIBlock) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_ui_proto_rawDescGZIP(), []int{2}
}

func (x *UIBlock) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

func (x *UIBlock) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UIBlock) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *UIBlock) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *UIBlock) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

func (x *UIBlock) GetHint() string {
	if x != nil {
		return x.Hint
	}
	return ""
}

func (x *UIBlock) GetVariant() string {
	if x != nil {
		return x.Variant
	}
	return ""
}

func (x *UIBlock) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *UIBlock) GetAlt() string {
	if x != nil {
		return x.Alt
	}
	return ""
}

func (x *UIBlock) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *UIBlock) GetOptions() []*SelectOption {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *UIBlock) GetStyle() string {
	if x != nil {
		return x.Style
	}
	return ""
}

// SelectOption is a single option in a select block.
type SelectOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectOption) Reset() {
	*x = SelectOption{}
	mi := &file_proto_apps_v0_ui_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectOption) ProtoMessage() {}

func (x *SelectOption) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_ui_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectOption.ProtoReflect.Descriptor instead.
func (*SelectOption) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_ui_proto_rawDescGZIP(), []int{3}
}

func (x *SelectOption) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *SelectOption) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// UIEvent is sent from Nebo to the app when a user interacts with a block.
type UIEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ViewId        string                 `protobuf:"bytes,1,opt,name=view_id,json=viewId,proto3" json:"view_id,omitempty"`    // Which view the event came from
	BlockId       string                 `protobuf:"bytes,2,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"` // Which block was interacted with
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`                  // "click", "change", "submit"
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`                    // New value (for inputs, selects, toggles)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UIEvent) Reset() {
	*x = UIEvent{}
	mi := &file_proto_apps_v0_ui_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIEvent) ProtoMessage() {}

func (x *UIEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_ui_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIEvent.ProtoReflect.Descriptor instead.
func (*UIEvent) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_ui_proto_rawDescGZIP(), []int{4}
}

func (x *UIEvent) GetViewId() string {
	if x != nil {
		return x.ViewId
	}
	return ""
}

func (x *UIEvent) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

func (x *UIEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *UIEvent) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// UIEventResponse is the app's response to a UI event.
type UIEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	View          *UIView                `protobuf:"bytes,1,opt,name=view,proto3" json:"view,omitempty"`   // Optional: updated view to replace the current one
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // Error message if the event handling failed
	Toast         string                 `protobuf:"bytes,3,opt,name=toast,proto3" json:"toast,omitempty"` // Optional: toast notification to show the user
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UIEventResponse) Reset() {
	*x = UIEventResponse{}
	mi := &file_proto_apps_v0_ui_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIEventResponse) ProtoMessage() {}

func (x *UIEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_ui_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIEventResponse.ProtoReflect.Descriptor instead.
func (*UIEventResponse) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_ui_proto_rawDescGZIP(), []int{5}
}

func (x *UIEventResponse) GetView() *UIView {
	if x != nil {
		return x.View
	}
	return nil
}

func (x *UIEventResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *UIEventResponse) GetToast() string {
	if x != nil {
		return x.Toast
	}
	return ""
}

var File_proto_apps_v0_ui_proto protoreflect.FileDescriptor

const file_proto_apps_v0_ui_proto_rawDesc = "" +
	"\n" +
	"\x16proto/apps/v0/ui.proto\x12\aapps.v0\x1a\x1aproto/apps/v0/common.proto\"*\n" +
	"\x0eGetViewRequest\x12\x18\n" +
	"\acontext\x18\x01 \x01(\tR\acontext\"a\n" +
	"\x06UIView\x12\x17\n" +
	"\aview_id\x18\x01 \x01(\tR\x06viewId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12(\n" +
	"\x06blocks\x18\x03 \x03(\v2\x10.apps.v0.UIBlockR\x06blocks\"\xb9\x02\n" +
	"\aUIBlock\x12\x19\n" +
	"\bblock_id\x18\x01 \x01(\tR\ablockId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12 \n" +
	"\vplaceholder\x18\x05 \x01(\tR\vplaceholder\x12\x12\n" +
	"\x04hint\x18\x06 \x01(\tR\x04hint\x12\x18\n" +
	"\avariant\x18\a \x01(\tR\avariant\x12\x10\n" +
	"\x03src\x18\b \x01(\tR\x03src\x12\x10\n" +
	"\x03alt\x18\t \x01(\tR\x03alt\x12\x1a\n" +
	"\bdisabled\x18\n" +
	" \x01(\bR\bdisabled\x12/\n" +
	"\aoptions\x18\v \x03(\v2\x15.apps.v0.SelectOptionR\aoptions\x12\x14\n" +
	"\x05style\x18\f \x01(\tR\x05style\":\n" +
	"\fSelectOption\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"k\n" +
	"\aUIEvent\x12\x17\n" +
	"\aview_id\x18\x01 \x01(\tR\x06viewId\x12\x19\n" +
	"\bblock_id\x18\x02 \x01(\tR\ablockId\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\"b\n" +
	"\x0fUIEventResponse\x12#\n" +
	"\x04view\x18\x01 \x01(\v2\x0f.apps.v0.UIViewR\x04view\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x14\n" +
	"\x05toast\x18\x03 \x01(\tR\x05toast2\xaa\x02\n" +
	"\tUIService\x12H\n" +
	"\vHealthCheck\x12\x1b.apps.v0.HealthCheckRequest\x1a\x1c.apps.v0.HealthCheckResponse\x123\n" +
	"\aGetView\x12\x17.apps.v0.GetViewRequest\x1a\x0f.apps.v0.UIView\x127\n" +
	"\tSendEvent\x12\x10.apps.v0.UIEvent\x1a\x18.apps.v0.UIEventResponse\x122\n" +
	"\rStreamUpdates\x12\x0e.apps.v0.Empty\x1a\x0f.apps.v0.UIView0\x01\x121\n" +
	"\tConfigure\x12\x14.apps.v0.SettingsMap\x1a\x0e.apps.v0.EmptyB$Z\"github.com/nebolabs/nebo-sdk-go/pbb\x06proto3"

var (
	file_proto_apps_v0_ui_proto_rawDescOnce sync.Once
	file_proto_apps_v0_ui_proto_rawDescData []byte
)

func file_proto_apps_v0_ui_proto_rawDescGZIP() []byte {
	file_proto_apps_v0_ui_proto_rawDescOnce.Do(func() {
		file_proto_apps_v0_ui_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_apps_v0_ui_proto_rawDesc), len(file_proto_apps_v0_ui_proto_rawDesc)))
	})
	return file_proto_apps_v0_ui_proto_rawDescData
}

var file_proto_apps_v0_ui_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_apps_v0_ui_proto_goTypes = []any{
	(*GetViewRequest)(nil),      // 0: apps.v0.GetViewRequest
	(*UIView)(nil),              // 1: apps.v0.UIView
	(*UIBlock)(nil),             // 2: apps.v0.UIBlock
	(*SelectOption)(nil),        // 3: apps.v0.SelectOption
	(*UIEvent)(nil),             // 4: apps.v0.UIEvent
	(*UIEventResponse)(nil),     // 5: apps.v0.UIEventResponse
	(*HealthCheckRequest)(nil),  // 6: apps.v0.HealthCheckRequest
	(*Empty)(nil),               // 7: apps.v0.Empty
	(*SettingsMap)(nil),         // 8: apps.v0.SettingsMap
	(*HealthCheckResponse)(nil), // 9: apps.v0.HealthCheckResponse
}
var file_proto_apps_v0_ui_proto_depIdxs = []int32{
	2, // 0: apps.v0.UIView.blocks:type_name -> apps.v0.UIBlock
	3, // 1: apps.v0.UIBlock.options:type_name -> apps.v0.SelectOption
	1, // 2: apps.v0.UIEventResponse.view:type_name -> apps.v0.UIView
	6, // 3: apps.v0.UIService.HealthCheck:input_type -> apps.v0.HealthCheckRequest
	0, // 4: apps.v0.UIService.GetView:input_type -> apps.v0.GetViewRequest
	4, // 5: apps.v0.UIService.SendEvent:input_type -> apps.v0.UIEvent
	7, // 6: apps.v0.UIService.StreamUpdates:input_type -> apps.v0.Empty
	8, // 7: apps.v0.UIService.Configure:input_type -> apps.v0.SettingsMap
	9, // 8: apps.v0.UIService.HealthCheck:output_type -> apps.v0.HealthCheckResponse
	1, // 9: apps.v0.UIService.GetView:output_type -> apps.v0.UIView
	5, // 10: apps.v0.UIService.SendEvent:output_type -> apps.v0.UIEventResponse
	1, // 11: apps.v0.UIService.StreamUpdates:output_type -> apps.v0.UIView
	7, // 12: apps.v0.UIService.Configure:output_type -> apps.v0.Empty
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_apps_v0_ui_proto_init() }
func file_proto_apps_v0_ui_proto_init() {
	if File_proto_apps_v0_ui_proto != nil {
		return
	}
	file_proto_apps_v0_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_apps_v0_ui_proto_rawDesc), len(file_proto_apps_v0_ui_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_apps_v0_ui_proto_goTypes,
		DependencyIndexes: file_proto_apps_v0_ui_proto_depIdxs,
		MessageInfos:      file_proto_apps_v0_ui_proto_msgTypes,
	}.Build()
	File_proto_apps_v0_ui_proto = out.File
	file_proto_apps_v0_ui_proto_goTypes = nil
	file_proto_apps_v0_ui_proto_depIdxs = nil
}
