// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.0
// source: proto/apps/v0/ui.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UIService_HealthCheck_FullMethodName   = "/apps.v0.UIService/HealthCheck"
	UIService_GetView_FullMethodName       = "/apps.v0.UIService/GetView"
	UIService_SendEvent_FullMethodName     = "/apps.v0.UIService/SendEvent"
	UIService_StreamUpdates_FullMethodName = "/apps.v0.UIService/StreamUpdates"
	UIService_Configure_FullMethodName     = "/apps.v0.UIService/Configure"
)

// UIServiceClient is the client API for UIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// UIService is the interface for apps that render structured UI in Nebo.
// Apps push JSON-described views; Nebo renders them with pre-built components.
// This is Tier 1 (structured templates) — no custom HTML/CSS/JS.
type UIServiceClient interface {
	// HealthCheck verifies the app is running.
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// GetView returns the current UI view for the app.
	GetView(ctx context.Context, in *GetViewRequest, opts ...grpc.CallOption) (*UIView, error)
	// SendEvent sends a user interaction event back to the app (button click, input change, etc.).
	SendEvent(ctx context.Context, in *UIEvent, opts ...grpc.CallOption) (*UIEventResponse, error)
	// StreamUpdates streams UI view updates from the app to Nebo.
	// Apps push new views whenever their UI state changes.
	StreamUpdates(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[UIView], error)
	// Configure updates the app's settings.
	Configure(ctx context.Context, in *SettingsMap, opts ...grpc.CallOption) (*Empty, error)
}

type uIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUIServiceClient(cc grpc.ClientConnInterface) UIServiceClient {
	return &uIServiceClient{cc}
}

func (c *uIServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, UIService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uIServiceClient) GetView(ctx context.Context, in *GetViewRequest, opts ...grpc.CallOption) (*UIView, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UIView)
	err := c.cc.Invoke(ctx, UIService_GetView_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uIServiceClient) SendEvent(ctx context.Context, in *UIEvent, opts ...grpc.CallOption) (*UIEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UIEventResponse)
	err := c.cc.Invoke(ctx, UIService_SendEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uIServiceClient) StreamUpdates(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[UIView], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &UIService_ServiceDesc.Streams[0], UIService_StreamUpdates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, UIView]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UIService_StreamUpdatesClient = grpc.ServerStreamingClient[UIView]

func (c *uIServiceClient) Configure(ctx context.Context, in *SettingsMap, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, UIService_Configure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UIServiceServer is the server API for UIService service.
// All implementations must embed UnimplementedUIServiceServer
// for forward compatibility.
//
// UIService is the interface for apps that render structured UI in Nebo.
// Apps push JSON-described views; Nebo renders them with pre-built components.
// This is Tier 1 (structured templates) — no custom HTML/CSS/JS.
type UIServiceServer interface {
	// HealthCheck verifies the app is running.
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// GetView returns the current UI view for the app.
	GetView(context.Context, *GetViewRequest) (*UIView, error)
	// SendEvent sends a user interaction event back to the app (button click, input change, etc.).
	SendEvent(context.Context, *UIEvent) (*UIEventResponse, error)
	// StreamUpdates streams UI view updates from the app to Nebo.
	// Apps push new views whenever their UI state changes.
	StreamUpdates(*Empty, grpc.ServerStreamingServer[UIView]) error
	// Configure updates the app's settings.
	Configure(context.Context, *SettingsMap) (*Empty, error)
	mustEmbedUnimplementedUIServiceServer()
}

// UnimplementedUIServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUIServiceServer struct{}

func (UnimplementedUIServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedUIServiceServer) GetView(context.Context, *GetViewRequest) (*UIView, error) {
	return nil, status.Error(codes.Unimplemented, "method GetView not implemented")
}
func (UnimplementedUIServiceServer) SendEvent(context.Context, *UIEvent) (*UIEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendEvent not implemented")
}
func (UnimplementedUIServiceServer) StreamUpdates(*Empty, grpc.ServerStreamingServer[UIView]) error {
	return status.Error(codes.Unimplemented, "method StreamUpdates not implemented")
}
func (UnimplementedUIServiceServer) Configure(context.Context, *SettingsMap) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Configure not implemented")
}
func (UnimplementedUIServiceServer) mustEmbedUnimplementedUIServiceServer() {}
func (UnimplementedUIServiceServer) testEmbeddedByValue()                   {}

// UnsafeUIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UIServiceServer will
// result in compilation errors.
type UnsafeUIServiceServer interface {
	mustEmbedUnimplementedUIServiceServer()
}

func RegisterUIServiceServer(s grpc.ServiceRegistrar, srv UIServiceServer) {
	// If the following call panics, it indicates UnimplementedUIServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UIService_ServiceDesc, srv)
}

func _UIService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UIServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UIService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UIServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UIService_GetView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UIServiceServer).GetView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UIService_GetView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UIServiceServer).GetView(ctx, req.(*GetViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UIService_SendEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UIEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UIServiceServer).SendEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UIService_SendEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UIServiceServer).SendEvent(ctx, req.(*UIEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _UIService_StreamUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UIServiceServer).StreamUpdates(m, &grpc.GenericServerStream[Empty, UIView]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UIService_StreamUpdatesServer = grpc.ServerStreamingServer[UIView]

func _UIService_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettingsMap)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UIServiceServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UIService_Configure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UIServiceServer).Configure(ctx, req.(*SettingsMap))
	}
	return interceptor(ctx, in, info, handler)
}

// UIService_ServiceDesc is the grpc.ServiceDesc for UIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "apps.v0.UIService",
	HandlerType: (*UIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _UIService_HealthCheck_Handler,
		},
		{
			MethodName: "GetView",
			Handler:    _UIService_GetView_Handler,
		},
		{
			MethodName: "SendEvent",
			Handler:    _UIService_SendEvent_Handler,
		},
		{
			MethodName: "Configure",
			Handler:    _UIService_Configure_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamUpdates",
			Handler:       _UIService_StreamUpdates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/apps/v0/ui.proto",
}
